gText_ApprenticeChallenge0::
	.string "Euh… Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1}.\nSnif… Ça me met la pression…$"

gText_ApprenticeChallenge1::
	.string "Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ! En avant !$"

gText_ApprenticeChallenge2::
	.string "Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ! Accepte mon défi !$"

gText_ApprenticeChallenge3::
	.string "Euh… Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1}…\n"
	.string "Tu crois que je peux gagner ?$"

gText_ApprenticeChallenge4::
	.string "Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ! Vas-y, défie-moi !$"

gText_ApprenticeChallenge5::
	.string "Je suis débordé, mais je suis aussi\n"
	.string "l'apprenti nº {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1}. Enchanté !$"

gText_ApprenticeChallenge7::
	.string "Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1}. Je peux commencer ?$"

gText_ApprenticeChallenge8::
	.string "Aïe ! Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ! Je vais me donner à fond !$"

gText_ApprenticeChallenge9::
	.string "Youhou ! Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ! En garde !$"

gText_ApprenticeChallenge10::
	.string "Je suis le 1000e apprenti de {STR_VAR_1} !\n"
	.string "Enfin… l'apprenti nº {STR_VAR_2} !\n"
	.string "C'est parti !$"

gText_ApprenticeChallenge11::
	.string "Ouais, je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ! On s'éclate !$"

gText_ApprenticeChallenge12::
	.string "Youpi-ya ! Je suis ce qu'on appelle\n"
	.string "l'apprenti nº {STR_VAR_2} de {STR_VAR_1} !$"

gText_ApprenticeChallenge13::
	.string "Kof ! Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1}. Enchanté ! Kof !$"

gText_ApprenticeChallenge14::
	.string "Ça me stresse…\n"
	.string "Je suis l'apprenti nº {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Je suis l'apprenti nº {STR_VAR_2}\n"
	.string "de {STR_VAR_1},\n"
	.string "et je ne mens pas.$"

gText_ApprenticePleaseTeach0::
	.string "Tu es… {PLAYER} ?\n"
	.string "Oh ! Snif… ouin…\p"
	.string "Oh ! D-désolé…\n"
	.string "Je suis si nerveux que je pleure…\p"
	.string "Je suis {STR_VAR_1}, et je t'admire\n"
	.string "beaucoup, {PLAYER}.\p"
	.string "J… J'ai toujours rêvé de te rencontrer\n"
	.string "et de te poser des questions POKéMON.\p"
	.string "S'il te plaît, {PLAYER} !\n"
	.string "Apprends-moi des choses\n"
	.string "sur les POKéMON !$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… M-mais…\n"
	.string "Snif… Ouaaaaaaah !\p"
	.string "S'il te plaît !\n"
	.string "Je t'en supplie !$"

gText_ApprenticeWhichLevelMode0::
	.string "Oh, vraiment ? Tu veux bien ?\n"
	.string "Génial ! Trop bien ! Wouhou !\p"
	.string "Oh… Désolé…\n"
	.string "Je suis si content que je pleure…\p"
	.string "Euh… Alors dis-moi !\n"
	.string "Ça concerne la TOUR DE COMBAT.\p"
	.string "Quel niveau est mieux pour moi :\n"
	.string "NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1} ?\n"
	.string "Ouaaaah !\p"
	.string "Oh ! Désolé !\n"
	.string "Tu m'as rendu si heureux\l"
	.string "en choisissant pour moi,\l"
	.string "que je pleure…\p"
	.string "Snif…\n"
	.string "Merci beaucoup !\l"
	.string "Reviens me parler, d'accord ?$"

gText_ApprenticePleaseTeach1::
	.string "Wahou ! Tu es {PLAYER}, pas vrai ?\n"
	.string "Tu es super fort, pas vrai ?\p"
	.string "Je suis {STR_VAR_1} !\n"
	.string "Je viens de devenir DRESSEUR !\p"
	.string "S'il te plaît, {PLAYER} !\n"
	.string "Tu peux être mon prof et m'apprendre\l"
	.string "plein de choses sur les DRESSEURS ?$"

gText_ApprenticeRejectTeaching1::
	.string "Hein ? Pourquoi ?\n"
	.string "Oh, s'il te plaît ? S'il te plaît !\l"
	.string "S'il te plaît, sois mon prof !$"

gText_ApprenticeWhichLevelMode1::
	.string "Oui ! Super !\p"
	.string "La première chose que je voulais te\n"
	.string "demander, c'est sur\l"
	.string "la TOUR DE COMBAT !\p"
	.string "Les salles NORMAL et DIFFICILE…\n"
	.string "Laquelle est faite pour moi ?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, hein ? C'est vrai !\n"
	.string "Je vais m'y donner à fond !\p"
	.string "Si on se revoit ici, apprends-moi\n"
	.string "autre chose, prof !$"

gText_ApprenticePleaseTeach2::
	.string "Euh… Tu es {PLAYER} ?\n"
	.string "Je m'appelle {STR_VAR_1}.\p"
	.string "Je veux devenir DRESSEUR POKéMON,\n"
	.string "mais je ne sais pas quoi faire…\p"
	.string "Alors je me suis dit que je pouvais te\n"
	.string "demander conseil, vu que tu es célèbre.\p"
	.string "{PLAYER}, tu peux me conseiller ?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, mais…\p"
	.string "Je veux vraiment devenir un DRESSEUR\n"
	.string "POKéMON !\p"
	.string "S'il te plaît, réponds à mes questions !$"

gText_ApprenticeWhichLevelMode2::
	.string "Merci !\n"
	.string "Voilà ma première question !\p"
	.string "La TOUR DE COMBAT a deux niveaux,\n"
	.string "NORMAL et DIFFICILE, c'est ça ?\p"
	.string "Quel niveau te semble le plus\n"
	.string "adapté pour moi ?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, le défi {STR_VAR_1} ?\n"
	.string "Compris !\p"
	.string "Si j'ai une autre question, je reviendrai\n"
	.string "ici te demander conseil !$"

gText_ApprenticePleaseTeach3::
	.string "Oh ? Hein ? Tu es…\n"
	.string "Non, c'est impossible.\p"
	.string "Il n'y a pas moyen qu'une personne\n"
	.string "comme moi rencontre {PLAYER}.\p"
	.string "…Tu es vraiment {PLAYER} ?\n"
	.string "J'arrive pas à croire que je te parle !\p"
	.string "Quand un truc aussi bien arrive,\n"
	.string "il va forcément m'arriver\l"
	.string "des horreurs après… je le sens…\p"
	.string "…Désolé…\n"
	.string "Je… je suis {STR_VAR_1}…\p"
	.string "Je n'ai rien de spécial\l"
	.string "dont je sois fier…\p"
	.string "Je devrais même pas parler de moi,\n"
	.string "tu vas m'oublier…\p"
	.string "J'ai toujours rêvé que\l"
	.string "si je te rencontrais,\l"
	.string "{PLAYER}, je pourrais te demander\l"
	.string "conseil en tant que DRESSEUR.\p"
	.string "Mais je ne pense pas que tu acceptes\n"
	.string "de faire ça.\p"
	.string "…Ou bien tu serais assez gentil pour\n"
	.string "me donner des conseils ?$"

gText_ApprenticeRejectTeaching3::
	.string "Je le savais…\p"
	.string "Ça devait arriver, je suis tellement\n"
	.string "nul et sans intérêt…\p"
	.string "Mais je me disais que, peut-être…\n"
	.string "Tu ne vas pas changer d'avis ?\p"
	.string "Mais je peux pas abandonner comme ça.\n"
	.string "Je te demande pendant que\l"
	.string "j'ai de la chance !\p"
	.string "S'il te plaît, tu peux me donner\n"
	.string "des conseils ?$"

gText_ApprenticeWhichLevelMode3::
	.string "Vraiment ? J'y crois pas !\n"
	.string "Tu vas vraiment me conseiller !\l"
	.string "Je… je suis si heureux…\p"
	.string "Ce que je veux te demander est\n"
	.string "bête, mais j'arrive pas à choisir…\p"
	.string "À la TOUR DE COMBAT, on peut choisir\n"
	.string "le niveau NORMAL ou DIFFICILE.\p"
	.string "Tu crois que j'ai une chance sur\n"
	.string "lequel ?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1} ? D'accord !\n"
	.string "Mais tu crois vraiment qu'une personne\l"
	.string "comme moi a une chance ?\p"
	.string "Je vais faire de mon mieux, même si je\n"
	.string "pense que ça marchera pas.\p"
	.string "Merci beaucoup d'avoir passé du temps\n"
	.string "avec quelqu'un comme moi.$"

gText_ApprenticePleaseTeach4::
	.string "Oh ! Tu es bien {PLAYER}{KUN}, pas vrai ?\p"
	.string "J'ai entendu dire que tu étais fort en\n"
	.string "POKéMON !\p"
	.string "Je suis {STR_VAR_1} !\n"
	.string "On va être amis !\p"
	.string "Tu sais ?\p"
	.string "Tu peux pas gagner à la\l"
	.string "ZONE DE COMBAT si tu ne sais\l"
	.string "que ce qu'on apprend à l'ÉCOLE\l"
	.string "DE DRESSEURS.\p"
	.string "Je suis prêt à écouter tes conseils.\n"
	.string "Tu acceptes, hein ?$"

gText_ApprenticeRejectTeaching4::
	.string "Hein ? Pourquoi tu refuses ?\n"
	.string "C'est moi qui te le demande !\l"
	.string "Tu dois changer d'avis !$"

gText_ApprenticeWhichLevelMode4::
	.string "Bon, il y a un truc.\n"
	.string "Je veux que tu décides pour moi.\p"
	.string "Tu sais que la TOUR DE COMBAT a des\n"
	.string "salles NORMAL et DIFFICILE ?\p"
	.string "Laquelle serait bien pour moi,\n"
	.string "{PLAYER}{KUN} ?$"

gText_ApprenticeLevelModeThanks4::
	.string "D'accord, {STR_VAR_1} me convient ?\n"
	.string "Merci !\p"
	.string "En sachant que c'est toi\l"
	.string "qui as décidé, {PLAYER}{KUN},\l"
	.string "je serai moins triste si je perds.\p"
	.string "Bon, je reviendrai te demander conseil.\n"
	.string "Salut !$"

gText_ApprenticePleaseTeach5::
	.string "Oh, salut ! {PLAYER}{KUN} !\n"
	.string "Je te connais, tu es célèbre !\l"
	.string "Moi, c'est {STR_VAR_1} ! Enchanté !\p"
	.string "Je suis TRIATHLÈTE, alors je reste en\n"
	.string "forme même en élevant des POKéMON.\p"
	.string "Je fais aussi d'autres choses comme\n"
	.string "travailler, faire la sieste, danser…\p"
	.string "Avec tout ça, c'est pas simple de\n"
	.string "devenir un bon DRESSEUR.\p"
	.string "Alors, j'ai une proposition !\p"
	.string "Si on s'est rencontrés,\l"
	.string "c'est pas pour rien. Alors\l"
	.string "{PLAYER}{KUN}, tu veux bien\l"
	.string "partager ta sagesse avec moi\l"
	.string "de temps en temps ?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, allez, s'il te plaît ?\n"
	.string "Un gars comme moi a besoin\l"
	.string "de quelqu'un comme toi,\l"
	.string "{PLAYER}{KUN} !\p"
	.string "Franchement, j'ai besoin\l"
	.string "de tes conseils !$"

gText_ApprenticeWhichLevelMode5::
	.string "Merci ! Voilà qui est mieux !\n"
	.string "Bon, on commence par facile !\p"
	.string "Tu sais que la TOUR DE COMBAT a\n"
	.string "deux niveaux, pas vrai ?\l"
	.string "Tu sais, NORMAL et DIFFICILE.\p"
	.string "Vu que je suis débordé,\l"
	.string "lequel je dois préparer ?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, hein ? OK, compris.\n"
	.string "Je vais trouver le temps et essayer !\p"
	.string "…Oups, je dois filer au boulot !\n"
	.string "Merci ! À plus !$"

gText_ApprenticePleaseTeach6::
	.string "Non ! C'est pas possible !\n"
	.string "Tu serais le vrai {PLAYER} ?\p"
	.string "Ah-ha ! Génial ! Je suis {STR_VAR_1},\n"
	.string "enchanté !\p"
	.string "{PLAYER}, tu es très fort,\n"
	.string "pas vrai ?\p"
	.string "Tout le monde parle de toi !\p"
	.string "Oh ! J'ai une super idée !\n"
	.string "Je vais te demander conseil, {PLAYER} !\l"
	.string "Je suis sûr que ça me rendra plus fort !\p"
	.string "C'est une bonne idée, non ?\n"
	.string "S'il te plaît, donne-moi des conseils !$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, tu peux faire le méchant,\n"
	.string "mais tu ne me trompes pas !\l"
	.string "Tu veux dire oui, hein ?$"

gText_ApprenticeWhichLevelMode6::
	.string "Oui ! Je savais que tu avais bon cœur,\n"
	.string "{PLAYER} !\p"
	.string "Qu'est-ce que je te demande d'abord ?\n"
	.string "…Oh, j'ai trouvé !\p"
	.string "Roulement de tambour !\n"
	.string "Ma question, c'est…\p"
	.string "Si je relève le défi\l"
	.string "de la TOUR DE COMBAT,\l"
	.string "je vais où ?\p"
	.string "NORMAL ou DIFFICILE ?\n"
	.string "Qu'est-ce qui me convient le mieux ?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh !\n"
	.string "Tu dis {STR_VAR_1} !\l"
	.string "Merci, c'est une réponse\l"
	.string "trop cool !\p"
	.string "Je crois que c'est tout\l"
	.string "ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticePleaseTeach7::
	.string "Je vous demande pardon, mais…\n"
	.string "Tu es {PLAYER} ?\p"
	.string "Je suis {STR_VAR_1}, et je suis ravi de\n"
	.string "faire ta connaissance.\p"
	.string "Je t'admire depuis longtemps…\p"
	.string "… … … … … …\p"
	.string "Euh… J'espère que ma demande n'est\n"
	.string "pas trop lourde, mais…\p"
	.string "Puis-je devenir ton apprenti,\n"
	.string "{PLAYER} ?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh… !\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Je crois que je me suis évanoui.\n"
	.string "Désolé, j'ai dû mal entendre.\p"
	.string "S'il te plaît ! Dis que tu acceptes\n"
	.string "de me prendre comme apprenti !$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Je suis ravi !\p"
	.string "Je ne veux pas te faire\l"
	.string "perdre ton temps,\n"
	.string "alors conseille-moi sur ceci.\p"
	.string "Je compte bientôt relever le défi de\n"
	.string "la TOUR DE COMBAT.\p"
	.string "Cependant, il y a deux niveaux…\p"
	.string "Lequel est le plus adapté pour moi ?\n"
	.string "NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks7::
	.string "Tu choisis {STR_VAR_1} !\n"
	.string "Je vois. Je ferai de mon mieux !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter\l"
	.string "sur toi encore.\l"
	.string "Prends soin de toi !$"

gText_ApprenticePleaseTeach8::
	.string "Aïe ! Aïe ! {PLAYER} !\n"
	.string "Tu m'as parlé !\l"
	.string "Je… je suis trop content !\p"
	.string "Moi ! Je m'appelle {STR_VAR_1} !\n"
	.string "Je viens de devenir DRESSEUR !\p"
	.string "Je suis ravi de te rencontrer,\l"
	.string "{PLAYER}, la célébrité\l"
	.string "du monde POKéMON !\p"
	.string "Oh-oh-oh, j'ai une idée !\n"
	.string "Je peux te demander\l"
	.string "un énorme service,\l"
	.string "{PLAYER} ?\p"
	.string "S'il te plaît, prends-moi comme apprenti !\n"
	.string "Je veux apprendre de toi !$"

gText_ApprenticeRejectTeaching8::
	.string "Ouaaah !\n"
	.string "{PLAYER} m'a refusé…\l"
	.string "C… C'est une expérience inoubliable !\p"
	.string "{PLAYER}, s'il te plaît ! Cette fois,\n"
	.string "je veux entendre oui !\p"
	.string "Je t'en supplie, guide-moi !$"

gText_ApprenticeWhichLevelMode8::
	.string "Hiiiii ! {PLAYER} a dit oui !\n"
	.string "{PLAYER} a dit oui !\p"
	.string "Je vais pas pouvoir dormir cette nuit…\n"
	.string "Merci mille fois !\p"
	.string "Alors, voilà ma question !\p"
	.string "À la TOUR DE COMBAT, qu'est-ce qui me\n"
	.string "convient : NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1} ! Parfaitement compris !\n"
	.string "J'ai tout compris !\l"
	.string "Je suis trop content !\p"
	.string "J'espère que tu voudras\l"
	.string "encore m'apprendre\n"
	.string "des choses une autre fois.$"

gText_ApprenticePleaseTeach9::
	.string "Wouah ! Tu serais…\n"
	.string "Tu serais… {PLAYER}{KUN} ?!\l"
	.string "Ce DRESSEUR fort et célèbre ?\l"
	.string "Eh bien, salut ! J'ai trop de chance !\p"
	.string "Salut, moi c'est {STR_VAR_1} !\p"
	.string "Je cherchais justement\n"
	.string "un prof POKéMON.\p"
	.string "Et au moment parfait,\n"
	.string "voilà que tu arrives, {PLAYER}{KUN} !\p"
	.string "Alors voilà, {PLAYER}{KUN} !\n"
	.string "Laisse-moi devenir ton apprenti !$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah !\n"
	.string "Tu es trop cool et trop fort…\p"
	.string "Ne fais pas ça, s'il te plaît.\n"
	.string "Je te le demande !$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, ouais ! Ça, c'est une réponse solide !\n"
	.string "Excellente, même !\p"
	.string "Alors, un premier conseil sur la\n"
	.string "TOUR DE COMBAT ?\p"
	.string "Si j'y vais, qu'est-ce qui est mieux ?\n"
	.string "NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, donc {STR_VAR_1} !\n"
	.string "OK, OK !\l"
	.string "Je vais montrer ce que je vaux !\p"
	.string "Bon, je te prends comme mentor !\n"
	.string "Adios !$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hé, {PLAYER}{KUN}, c'est ça ?\n"
	.string "La police te cherchait !\p"
	.string "… … …\n"
	.string "Bien sûr que je mens !\p"
	.string "Moi, je suis {STR_VAR_1}.\l"
	.string "Malgré mon air,\n"
	.string "je suis le CHAMPION POKéMON !\l"
	.string "…Ça aussi, c'est faux !\p"
	.string "Mais ça, c'est vrai.\n"
	.string "Je suis pas très bon en combat.\p"
	.string "Alors, tu veux bien\l"
	.string "devenir mon maître\n"
	.string "pour tout ce qui touche\l"
	.string "aux POKéMON ?$"

gText_ApprenticeRejectTeaching10::
	.string "Si tu fais le froid comme ça,\n"
	.string "je vais te montrer ce que je fais !\p"
	.string "Ouin ! Ouin ! Ouin !\n"
	.string "Hic !\p"
	.string "Hahaha, c'était mes FAUSSES LARMES !\p"
	.string "Allez, tu veux bien être\n"
	.string "mon maître POKéMON ?$"

gText_ApprenticeWhichLevelMode10::
	.string "Youpi !\n"
	.string "Je t'achète un bateau pour ça !\p"
	.string "Bien sûr que je mens encore !\n"
	.string "Mais… merci, maître !\p"
	.string "Tu sais qu'il y a un\l"
	.string "niveau NORMAL et\n"
	.string "DIFFICILE à la TOUR DE COMBAT ?\p"
	.string "J'arrive pas à décider lequel\n"
	.string "je dois tenter…\p"
	.string "Tu peux décider pour\l"
	.string "moi, maître ?$"

gText_ApprenticeLevelModeThanks10::
	.string "D'accord, donc {STR_VAR_1}\l"
	.string "c'est mieux !\n"
	.string "Alors je vais à l'autre niveau !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu\l"
	.string "continueras à m'apprendre !$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y !\n"
	.string "Ça se lit “ahoy”,\l"
	.string "et ça veut dire salut !\p"
	.string "Je suis {STR_VAR_1}, le MARIN rappeur,\n"
	.string "c'est moi !\p"
	.string "À ton tour, dis-moi\l"
	.string "un peu qui tu es,\n"
	.string "vas-y, essaie !\p"
	.string "Uh-huh, uh-huh !\n"
	.string "Ton nom c'est {PLAYER}{KUN},\l"
	.string "et les POKéMON, c'est ton truc !\p"
	.string "Tu es à l'âge délicat\n"
	.string "où le monde est ta scène !\p"
	.string "Bref, je veux juste te dire\n"
	.string "que tu es le dixième DRESSEUR\l"
	.string "à qui je parle aujourd'hui.\p"
	.string "On va fêter ça !\n"
	.string "Deviens mon mentor,\l"
	.string "pour la commémoration !$"

gText_ApprenticeRejectTeaching11::
	.string "Mais !\n"
	.string "Tu dois bosser avec moi !\p"
	.string "Ne fais pas ton timide !\n"
	.string "Deviens mon mentor, s'il te plaît !$"

gText_ApprenticeWhichLevelMode11::
	.string "Voilà !\n"
	.string "{PLAYER}, tu as l'esprit !\p"
	.string "Voici ma première question,\n"
	.string "et j'attends ta suggestion !\p"
	.string "C'est sur la TOUR DE COMBAT,\n"
	.string "et ça dépend de ma force !\p"
	.string "Il y a NORMAL et DIFFICILE,\n"
	.string "lequel est bon pour moi ?$"

gText_ApprenticeLevelModeThanks11::
	.string "OK, tu dis {STR_VAR_1} !\n"
	.string "J'y vais, je me lance !\p"
	.string "Si j'ai besoin d'un conseil,\n"
	.string "{PLAYER}, j'écouterai toujours ta voix !$"

gText_ApprenticePleaseTeach12::
	.string "Dis, hé, tu serais pas\l"
	.string "{PLAYER} ?\n"
	.string "Je fais quoi ? Je te parle ?\l"
	.string "Pourquoi pas ? Je te parle déjà !\p"
	.string "{PLAYER}, tu es surpris, hein ?\n"
	.string "Je ferais mieux de me présenter !\p"
	.string "On m'appelle {STR_VAR_1}.\n"
	.string "La star des guitares,\l"
	.string "c'est moi !\p"
	.string "Tu m'entends bien ?\n"
	.string "Tu m'entends bien !\p"
	.string "J'ai trop de chance,\n"
	.string "alors j'ai une demande !\p"
	.string "{PLAYER}, prends-moi comme apprenti !\n"
	.string "Je veux que tu m'apprennes tout !$"

gText_ApprenticeRejectTeaching12::
	.string "Tu me refuses, c'est ça ?\n"
	.string "Alors je vais te redemander !\p"
	.string "{PLAYER}, prends-moi comme apprenti !\n"
	.string "J'ai besoin que tu\l"
	.string "m'apprennes tout !$"

gText_ApprenticeWhichLevelMode12::
	.string "Chanceux, ouais, wouhou !\n"
	.string "Je peux te poser une question ?\p"
	.string "Comme on est près de la TOUR DE COMBAT,\n"
	.string "une question sur son niveau, ça te va ?\p"
	.string "Entre NORMAL et DIFFICILE,\n"
	.string "lequel est fait pour moi ?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si tu dis {STR_VAR_1},\n"
	.string "alors c'est ce qu'il y a de mieux !\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticePleaseTeach13::
	.string "Oh, salut ! Hé, toi !\n"
	.string "Tu peux me masser l'épaule ?\p"
	.string "…Oui, là ! C'est ça !\n"
	.string "Aïe, aïe ! Ooooh, ça fait du bien !\p"
	.string "Je m'appelle {STR_VAR_1}.\n"
	.string "Je m'entraîne au karaté,\l"
	.string "mais mon corps supporte\l"
	.string "mal les coups…\p"
	.string "J'ai décidé de combattre\l"
	.string "avec des POKéMON\n"
	.string "pour me renforcer.\p"
	.string "Tu es {PLAYER}{KUN}, pas vrai ?\n"
	.string "Le CHAMPION de la LIGUE POKéMON ?\p"
	.string "Écoute, tu peux me donner\n"
	.string "des conseils ?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, pourquoi ?\p"
	.string "Je te dérangerai pas beaucoup, promis !\n"
	.string "S'il te plaît ?$"

gText_ApprenticeWhichLevelMode13::
	.string "Merci. C'est sympa\l"
	.string "de ta part !\n"
	.string "…Kof ! Kof !\p"
	.string "Oogh, je dois vite me renforcer…\p"
	.string "Je file à la TOUR DE COMBAT\l"
	.string "tout de suite, mais\l"
	.string "qu'est-ce qui est mieux pour moi ?\l"
	.string "NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hmm, d'accord. Donc {STR_VAR_1}.\n"
	.string "J'y vais tout de suite.\p"
	.string "J'espère pouvoir continuer\l"
	.string "à te demander de l'aide…\l"
	.string "Après tout, tu es mon mentor !$"

gText_ApprenticePleaseTeach14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}… ?\p"
	.string "S'il te plaît, ne me\l"
	.string "regarde pas comme ça.\n"
	.string "Ça me met mal à l'aise.\p"
	.string "Je… je suis {STR_VAR_1}.\p"
	.string "C'est vraiment gênant à dire,\n"
	.string "mais j'explore des ruines\l"
	.string "anciennes et tout.\p"
	.string "Et c'est encore plus gênant\l"
	.string "d'avouer\n"
	.string "que la ZONE DE COMBAT m'intéresse.\p"
	.string "{PLAYER}{KUN}, tu as la\l"
	.string "réputation d'être\n"
	.string "un DRESSEUR coriace…\p"
	.string "C'est dur à dire,\n"
	.string "mais je veux te demander quelque chose.\p"
	.string "Tu peux être mon prof et\n"
	.string "me donner des conseils ?$"

gText_ApprenticeRejectTeaching14::
	.string "S'il te plaît, ne me\l"
	.string "rejette pas comme ça !\n"
	.string "Je ne supporterais pas l'humiliation.\p"
	.string "S'il te plaît, deviens mon prof !\n"
	.string "J'ai besoin de tes conseils !$"

gText_ApprenticeWhichLevelMode14::
	.string "M-merci…\p"
	.string "Mais s'il te plaît,\l"
	.string "ne me regarde pas comme ça.\n"
	.string "Je suis tout gêné.\p"
	.string "S'il te plaît, réponds sans\n"
	.string "me regarder dans les yeux.\p"
	.string "À la TOUR DE COMBAT…\n"
	.string "Quel niveau je dois tenter ?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais tenter ça.\p"
	.string "J'espère réussir un beau défi\n"
	.string "sans être trop gêné…\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit,\l"
	.string "j'espère que tu seras\l"
	.string "encore aussi serviable.$"

gText_ApprenticePleaseTeach15::
	.string "Hmm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais est-ce bien vrai ?\p"
	.string "Tu peux m'appeler {STR_VAR_1}.\p"
	.string "Je réfléchissais à devenir l'apprenti\n"
	.string "d'un DRESSEUR puissant.\p"
	.string "Je dois dire que j'ai de la\l"
	.string "chance que tu passes !\n"
	.string "…Tu es bien {PLAYER}{KUN}, oui ?\p"
	.string "Non, non, si tu es réel, ça me va.\n"
	.string "Je veux seulement que\l"
	.string "tu me reconnaisses\l"
	.string "comme ton apprenti.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh ?\n"
	.string "Mais qu'est-ce qui\l"
	.string "te pousse à refuser ?\p"
	.string "Je m'excuse d'avoir douté\n"
	.string "de ton identité.\p"
	.string "S'il te plaît, accepte\l"
	.string "mes excuses et\n"
	.string "prends-moi comme apprenti.$"

gText_ApprenticeWhichLevelMode15::
	.string "Tu m'acceptes vraiment ?\n"
	.string "Je ne veux pas fêter ça trop vite.\p"
	.string "Si c'est vrai, je m'excuse.\n"
	.string "Mais maintenant, j'ai besoin de tes conseils.\p"
	.string "Si j'entre à la TOUR DE COMBAT,\n"
	.string "qu'est-ce qui me conviendrait ?\l"
	.string "NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1} ?\n"
	.string "Tu en es sûr ?\p"
	.string "Je vois. Dans ce cas, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "Je sais que je peux être\l"
	.string "agaçant, mais\n"
	.string "je suis ravi que tu m'acceptes.\p"
	.string "Reviens me voir !$"

gText_ApprenticeWhatHeldItem0::
	.string "Soupir… Snif…\n"
	.string "Oh, {PLAYER} !\p"
	.string "Je suis coincé dans un dilemme\n"
	.string "et j'arrive pas à décider.\p"
	.string "Je sais pas quel objet je dois faire\n"
	.string "tenir à {STR_VAR_1}.\p"
	.string "Dis-moi, {PLAYER}.\n"
	.string "Quel objet tu me conseilles ?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, vraiment ? Je ne dois rien faire\n"
	.string "tenir à {STR_VAR_1} ?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, d'accord ! C'est réglé, super !\n"
	.string "Génial ! Trop bien ! Wouhou !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, je suis si content…\n"
	.string "Je crois que j'ai aussi\l"
	.string "l'objet {STR_VAR_1}.\p"
	.string "C'est réglé, super !\n"
	.string "Génial ! Trop bien ! Wouhou !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Ouaaah ! Sois pas méchant !\p"
	.string "On m'a déjà conseillé\l"
	.string "l'objet {STR_VAR_1},\n"
	.string "snif…\p"
	.string "Ou alors tu veux dire que je ne dois rien\n"
	.string "faire tenir à {STR_VAR_2} ?$"

gText_ApprenticeWhatHeldItem1::
	.string "Oui ! C'est {PLAYER} !\n"
	.string "Super ! Je voulais te demander un truc !\p"
	.string "Tu fais tenir des objets\l"
	.string "à tes POKéMON ?\n"
	.string "Je veux le faire aussi, mais…\p"
	.string "Quel objet serait bien à faire tenir\n"
	.string "à {STR_VAR_1} ?\p"
	.string "Tu en penses quoi ?$"

gText_ApprenticeHoldNothing1::
	.string "Hein ? Tu veux dire que {STR_VAR_1}\n"
	.string "n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, j'ai compris ! Je vais faire ça !\n"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, wouah ! Un {STR_VAR_1}, hein ?\n"
	.string "D'accord, je vais faire ça !\p"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, euh, non, c'est pas\l"
	.string "ce que je voulais dire.\n"
	.string "Je veux connaître un autre objet\l"
	.string "que ceux que je connais déjà.\p"
	.string "Ou alors tu veux dire que mon POKéMON\n"
	.string "n'a pas besoin de tenir\l"
	.string "d'objet cette fois ?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, salut !\n"
	.string "C'est à propos de {STR_VAR_1}…\p"
	.string "Je veux lui faire tenir un bon objet.\n"
	.string "Qu'est-ce qui serait bien ?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, alors {STR_VAR_1} n'a pas besoin\n"
	.string "de tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "D'accord, compris !\n"
	.string "À la prochaine !$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, l'objet {STR_VAR_1} ?\n"
	.string "Compris !\p"
	.string "Je vais faire de mon\l"
	.string "mieux pour en trouver un !\n"
	.string "À la prochaine !$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Quelqu'un m'a déjà parlé\n"
	.string "de {STR_VAR_1}.\p"
	.string "Je veux que mon POKéMON tienne\n"
	.string "un autre type d'objet.\p"
	.string "Ou tu crois que\l"
	.string "{STR_VAR_2} n'a pas besoin\n"
	.string "de tenir d'objet ?$"

gText_ApprenticeWhatHeldItem3::
	.string "Salut, {PLAYER}…\n"
	.string "Désolé de te déranger, mais je voulais\l"
	.string "te demander autre chose.\p"
	.string "Je ne pense pas être\l"
	.string "assez bon pour gagner\n"
	.string "tout seul, alors je pense faire tenir\l"
	.string "un objet à {STR_VAR_1}.\p"
	.string "Mais je sais pas lequel serait bien.\p"
	.string "{PLAYER}, s'il te plaît,\l"
	.string "tu peux décider\n"
	.string "pour moi ?$"

gText_ApprenticeHoldNothing3::
	.string "Un POKéMON à quelqu'un comme moi\n"
	.string "serait mieux sans objet ?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Je comprends…\n"
	.string "Tu dis que je ne dois\l"
	.string "pas compter sur les objets.\l"
	.string "Je vais essayer de ne pas le faire !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeThanksHeldItem3::
	.string "L'objet {STR_VAR_1}, d'accord.\n"
	.string "Je sais pas si je peux en obtenir un…\l"
	.string "Non ! Je vais faire de mon mieux !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, mais…\n"
	.string "Je crois que j'en ai déjà entendu parler…\p"
	.string "C'est parce que je ne\l"
	.string "me suis pas bien servi\n"
	.string "de l'objet {STR_VAR_1} ?\p"
	.string "Ou alors tu veux dire que je ne dois rien\n"
	.string "faire tenir à {STR_VAR_2} ?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Je voulais te demander quelque chose.\p"
	.string "Tu sais quand tu as décidé quel\n"
	.string "POKéMON je devais avoir ?\p"
	.string "Mais je ne t'ai jamais\l"
	.string "demandé quel objet\n"
	.string "il devait tenir.\p"
	.string "Puisque tu m'as déjà conseillé,\n"
	.string "autant aller jusqu'au bout, non ?\p"
	.string "Qu'est-ce qui serait bien ?\l"
	.string "Je veux faire tenir quelque\l"
	.string "chose à {STR_VAR_1}.$"

gText_ApprenticeHoldNothing4::
	.string "Oh ! Donc {STR_VAR_1} doit faire\n"
	.string "de son mieux sans objet ?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si tu penses que c'est le mieux,\l"
	.string "je ferai ça.\p"
	.string "En sachant que c'est toi\l"
	.string "qui as décidé, {PLAYER}{KUN},\l"
	.string "je serai moins triste si je perds.\p"
	.string "Bon, je reviendrai te demander conseil.\n"
	.string "Salut !$"

gText_ApprenticeThanksHeldItem4::
	.string "L'objet {STR_VAR_1}, hein ?\n"
	.string "Pas mal. Je vais l'utiliser !\p"
	.string "En sachant que c'est toi\l"
	.string "qui as décidé, {PLAYER}{KUN},\l"
	.string "je serai moins triste si je perds.\p"
	.string "Bon, je reviendrai te demander conseil.\n"
	.string "Salut !$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hein ? Qu'est-ce que tu dis ?\n"
	.string "Tu m'as déjà parlé de {STR_VAR_1}.\l"
	.string "Tu t'en souviens, non ?\p"
	.string "Ou alors tu veux dire\l"
	.string "que {STR_VAR_2} doit\n"
	.string "faire de son mieux sans objet ?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN} !\p"
	.string "On est tous les deux débordés, mais on se\n"
	.string "croise quand même souvent !\p"
	.string "Aujourd'hui je dois marcher un peu,\n"
	.string "nettoyer, et me brosser.\p"
	.string "J'ai même pas eu le temps d'acheter\n"
	.string "quoi que ce soit à mon\l"
	.string "précieux {STR_VAR_1}.\p"
	.string "J'ai pas le temps,\l"
	.string "alors conseille-moi :\n"
	.string "quel objet je dois faire tenir\l"
	.string "à {STR_VAR_1} ?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, donc vu que je suis débordé,\n"
	.string "{STR_VAR_1} n'a besoin de rien ?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "OK, compris.\n"
	.string "Ça me prendra pas de temps.\p"
	.string "Merci pour aujourd'hui !\n"
	.string "À plus !$"

gText_ApprenticeThanksHeldItem5::
	.string "OK, compris.\n"
	.string "Je vais trouver le temps pour obtenir\l"
	.string "le {STR_VAR_1}\l"
	.string "que tu as conseillé.\p"
	.string "Je suis content d'avoir un bon mentor.\n"
	.string "Merci ! À plus !$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hein ? Je connais déjà\n"
	.string "{STR_VAR_1}.\p"
	.string "Ah, je vois.\n"
	.string "Donc, vu que je suis débordé,\l"
	.string "{STR_VAR_2} n'a besoin\l"
	.string "de rien ?$"

gText_ApprenticeWhatHeldItem6::
	.string "Salut, {PLAYER} ! C'est moi !\n"
	.string "J'ai encore besoin de tes conseils.\l"
	.string "S'il te plaît, aide-moi !\p"
	.string "Roulement de tambour !\n"
	.string "Ma question, c'est…\p"
	.string "Si je veux faire tenir un objet\n"
	.string "à {STR_VAR_1}, lequel ?$"

gText_ApprenticeHoldNothing6::
	.string "C'est ça ? Tu dis que {STR_VAR_1} n'a pas\n"
	.string "besoin de tenir d'objet.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "D'accord, je vais faire ça !\p"
	.string "Je crois que c'est tout\l"
	.string "ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeThanksHeldItem6::
	.string "Uh-huh ! Un {STR_VAR_1}.\n"
	.string "Quel choix trop cool !\l"
	.string "Je vais essayer, c'est sûr !\p"
	.string "Je crois que c'est tout\l"
	.string "ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahaha ! C'est bête !\n"
	.string "Tu m'as déjà parlé de\l"
	.string "{STR_VAR_1} !\p"
	.string "Tu vas bien, {PLAYER} ?\p"
	.string "Oh, attends ! Tu veux dire\l"
	.string "que {STR_VAR_2} n'a pas\n"
	.string "besoin de tenir d'objet.$"

gText_ApprenticeWhatHeldItem7::
	.string "Bonjour, {PLAYER}.\l"
	.string "J'espère que tu vas\n"
	.string "bien.\p"
	.string "Puis-je te demander conseil ?\p"
	.string "Lors d'un combat récent, mon adversaire\n"
	.string "semblait avoir fait tenir un objet\l"
	.string "à son POKéMON.\p"
	.string "Résultat : j'ai perdu…\p"
	.string "Je ne veux pas rester à la traîne.\n"
	.string "Je voudrais aussi faire tenir un objet\l"
	.string "à {STR_VAR_1}.\p"
	.string "Ça me ferait plaisir si\l"
	.string "tu pouvais décider de\l"
	.string "ce qui convient à mon\l"
	.string "POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "Autrement dit… Mon POKéMON\n"
	.string "n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "J'ai bien compris !\n"
	.string "Je vais continuer comme ça.\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter\l"
	.string "sur toi encore.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeThanksHeldItem7::
	.string "Donc un {STR_VAR_1} !\n"
	.string "Je vais en chercher tout de suite.\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter\l"
	.string "sur toi encore.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Tu m'en as déjà parlé,\n"
	.string "et je l'ai déjà.\p"
	.string "Ou alors tu veux dire… Mon POKéMON\n"
	.string "n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeWhatHeldItem8::
	.string "Aïe ! {PLAYER} !\n"
	.string "Je… je suis trop content de te revoir !\p"
	.string "Oh-oh-oh ! Il fallait que je te demande\n"
	.string "un truc, {PLAYER} !\p"
	.string "S'il te plaît, décide de ce que\n"
	.string "{STR_VAR_1} doit tenir !$"

gText_ApprenticeHoldNothing8::
	.string "Oh, wouah ! Je m'attendais pas à ça !\n"
	.string "Donc, un objet n'est pas nécessaire ?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Parfaitement compris !\n"
	.string "Je vais continuer sans objet !\p"
	.string "J'espère que tu voudras\l"
	.string "encore m'apprendre\n"
	.string "des choses une autre fois.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1} ! Je vais utiliser ça !\p"
	.string "Euh… Dis, {PLAYER},\l"
	.string "toi aussi tu fais\n"
	.string "tenir cet objet à tes POKéMON ?\p"
	.string "Je vais être sûr de l'obtenir !\n"
	.string "J'espère que tu voudras\l"
	.string "encore m'apprendre\l"
	.string "des choses une autre fois.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh ? Tu m'as déjà conseillé\n"
	.string "{STR_VAR_1} aussi.\p"
	.string "Ou c'est vraiment le meilleur objet ?\n"
	.string "Ou alors tu veux dire que {STR_VAR_2}\l"
	.string "n'a besoin de rien\l"
	.string "tenir ?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola !\n"
	.string "Mon maestro, {PLAYER}{KUN} !\p"
	.string "Je veux te demander conseil sur\n"
	.string "les outils POKéMON.\p"
	.string "À ton avis, qu'est-ce qui serait bien\n"
	.string "à faire tenir à {STR_VAR_1} ?\p"
	.string "Ne sois pas timide.\n"
	.string "Balance !$"

gText_ApprenticeHoldNothing9::
	.string "Oh ? Donc tu dis que {STR_VAR_1}\n"
	.string "peut gagner sans tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Sí, bueno !\n"
	.string "Je vais me donner à fond, bam !\p"
	.string "Bon, merci, comme toujours !\n"
	.string "Adios !$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, donc un {STR_VAR_1} ?\n"
	.string "Sí, bueno !\l"
	.string "Je vais en trouver un, bam !\p"
	.string "Bon, merci, comme toujours !\n"
	.string "Adios !$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Non, non ! Tu m'as déjà parlé\n"
	.string "de ce truc {STR_VAR_1}.\p"
	.string "Oh, attends une minute…\n"
	.string "Donc tu dis que {STR_VAR_2}\l"
	.string "peut gagner sans tenir d'objet ?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, un truc incroyable\n"
	.string "est arrivé !\p"
	.string "Je me suis réveillé ce matin,\l"
	.string "et mon POKéMON\n"
	.string "avait 10 PÉPITES !\p"
	.string "Bien sûr que je mens !\n"
	.string "Wahahaha !\p"
	.string "Mais ça, c'est vrai.\n"
	.string "Je suis pas très bon\l"
	.string "pour savoir quels objets\l"
	.string "les POKéMON doivent tenir.\p"
	.string "Alors, tu peux décider\l"
	.string "pour moi de ce que\n"
	.string "{STR_VAR_1} doit tenir, maître ?$"

gText_ApprenticeHoldNothing10::
	.string "Hein ? Ça veut dire quoi ?\n"
	.string "Je ne dois rien lui faire tenir ?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "D'accord, donc il ne doit rien tenir.\n"
	.string "Alors je dois lui acheter quelque chose !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu\l"
	.string "continueras à m'apprendre !$"

gText_ApprenticeThanksHeldItem10::
	.string "D'accord, donc un {STR_VAR_1} !\n"
	.string "Je lui ferai tenir\l"
	.string "n'importe quoi sauf ça !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu\l"
	.string "continueras à m'apprendre !$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Euh, tu m'en as déjà parlé,\n"
	.string "pas vrai ?\p"
	.string "Y a pas autre chose ?\p"
	.string "Ou alors tu veux dire : je ne dois rien\n"
	.string "faire tenir à {STR_VAR_2} ?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y !\n"
	.string "Ça se lit “ahoy” !\p"
	.string "Le MARIN rappeur, c'est moi !\n"
	.string "J'ai une question\l"
	.string "trop stylée, ma foi !\p"
	.string "C'est une question d'objet\n"
	.string "et j'attends ta suggestion !\p"
	.string "{STR_VAR_1} doit tenir un objet,\n"
	.string "lequel, si tu oses le dire ?$"

gText_ApprenticeHoldNothing11::
	.string "C'est ça ?\n"
	.string "{STR_VAR_1} n'a pas besoin de\l"
	.string "tenir quoi que ce soit ?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "OK, je t'entends, c'est clair !\n"
	.string "Mon POKéMON ira aussi sans objet !\p"
	.string "Si j'ai besoin d'un conseil,\n"
	.string "{PLAYER}, j'écouterai\l"
	.string "toujours tes paroles !$"

gText_ApprenticeThanksHeldItem11::
	.string "OK, un {STR_VAR_1},\n"
	.string "c'est ce que je vais utiliser.\l"
	.string "J'ai bien fait de te demander !\p"
	.string "Si j'ai besoin d'un conseil,\n"
	.string "{PLAYER}, j'écouterai\l"
	.string "toujours tes paroles !$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "OK, un {STR_VAR_1}, tu dis ?\n"
	.string "Tu m'as dit ça l'autre jour.\l"
	.string "J'ai besoin d'une nouvelle idée.\p"
	.string "Ou alors, c'est ça ?\n"
	.string "Mon POKéMON n'a pas besoin de\l"
	.string "tenir quoi que ce soit ?$"

gText_ApprenticeWhatHeldItem12::
	.string "Dis, hé, {PLAYER} !\n"
	.string "Je t'ai retrouvé aujourd'hui !\p"
	.string "Je fais quoi ? Je te demande conseil ?\n"
	.string "Pourquoi pas ? Je te parle déjà !\p"
	.string "{PLAYER}, tu en as marre de moi ?\n"
	.string "Non, pas possible, impossible.\p"
	.string "Tu m'écoutes ?\n"
	.string "Je cherche un conseil, c'est\l"
	.string "de ça que je parle.\p"
	.string "C'est pour un objet à faire tenir\n"
	.string "à {STR_VAR_1}.\l"
	.string "Mon hésitation me rend fou.$"

gText_ApprenticeHoldNothing12::
	.string "{STR_VAR_1} n'a besoin de rien ?\n"
	.string "Il n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Si ne rien tenir, c'est le mieux,\n"
	.string "je ferai comme tu dis !\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeThanksHeldItem12::
	.string "Si tenir {STR_VAR_1} est\n"
	.string "le mieux, je ferai comme tu dis !\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "J'en ai pas déjà entendu parler,\n"
	.string "de {STR_VAR_1} ?\l"
	.string "Si, c'est sûr !\p"
	.string "J'ai besoin d'un autre truc !\n"
	.string "Ou alors {STR_VAR_2}\l"
	.string "n'a besoin de rien ?\l"
	.string "Il n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah ! Aïe ! {PLAYER}{KUN},\l"
	.string "je me suis cassé le bras !\n"
	.string "Ne le touche pas, s'il te plaît !\p"
	.string "Je crois que je l'ai cassé en testant\n"
	.string "plein d'objets tenus avec ma bande\l"
	.string "de POKéMON.\p"
	.string "Donc, vu la situation,\n"
	.string "j'ai besoin que tu décides pour moi.\p"
	.string "{PLAYER}{KUN}, à ton avis,\l"
	.string "qu'est-ce qui serait bien\l"
	.string "à faire tenir à {STR_VAR_1} ?$"

gText_ApprenticeHoldNothing13::
	.string "Aïe…\p"
	.string "Donc tu dis que {STR_VAR_1}\n"
	.string "n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hmm, d'accord. Ce sera plus simple\n"
	.string "pour moi, vu l'état actuel.\p"
	.string "J'espère pouvoir continuer à te demander\n"
	.string "de l'aide comme ça.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hmm, d'accord. Donc un {STR_VAR_1}.\n"
	.string "Le bras de mon POKéMON va bien,\l"
	.string "alors je vais\l"
	.string "lui faire tenir ça tout de suite.\p"
	.string "J'espère pouvoir continuer à te demander\n"
	.string "de l'aide comme ça.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Non, non, tu m'as déjà parlé\n"
	.string "de {STR_VAR_1}, tu te souviens ?\p"
	.string "Tu peux pas me dire\n"
	.string "un truc encore mieux ?\p"
	.string "Oh, attends une seconde.\n"
	.string "Donc tu dis que {STR_VAR_2}\l"
	.string "n'a pas besoin de tenir d'objet ?$"

gText_ApprenticeWhatHeldItem14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "S'il te plaît, ne me\l"
	.string "regarde pas comme ça.\n"
	.string "Mes POKéMON n'ont rien.\p"
	.string "Je… C'est vraiment gênant,\n"
	.string "mais j'ai vraiment besoin\l"
	.string "de tes conseils.\p"
	.string "J'arrive pas à décider\l"
	.string "quel objet tenu\n"
	.string "rendrait {STR_VAR_1} plus fort.\p"
	.string "{PLAYER}{KUN}, à ton avis,\n"
	.string "qu'est-ce qui serait bien ?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Donc tu penses\l"
	.string "que ce serait mieux\n"
	.string "si {STR_VAR_1} n'avait pas d'objet ?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… D'accord !\n"
	.string "Je vais y aller sans objet.\p"
	.string "Ça me stresse quand même.\n"
	.string "Ce serait pas trop cool ?\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit,\l"
	.string "j'espère que tu seras\l"
	.string "encore aussi serviable.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… D'accord !\n"
	.string "Je vais y aller avec {STR_VAR_1}.\p"
	.string "Ça me stresse quand même.\n"
	.string "Ce serait pas trop cool ?\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit,\l"
	.string "j'espère que tu seras\l"
	.string "encore aussi serviable.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "M-mais j'en ai déjà entendu parler.\p"
	.string "S'il te plaît, ne me\l"
	.string "rejette pas comme ça !\n"
	.string "Je ne supporterais pas l'humiliation.\p"
	.string "Oh… Je me fais des idées ?\n"
	.string "Tu penses que ce serait mieux si\l"
	.string "{STR_VAR_2} n'avait pas d'objet ?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hmm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais est-ce bien vrai ?\l"
	.string "Un jumeau, peut-être ?\p"
	.string "Oh, non, non, non,\l"
	.string "ne t'inquiète pas !\n"
	.string "Si tu es vraiment {PLAYER},\l"
	.string "oublie mon impolitesse.\p"
	.string "Ce que je veux, c'est encore\n"
	.string "un peu de tes précieux conseils.\p"
	.string "Voici mon {STR_VAR_1},\l"
	.string "et je voudrais\n"
	.string "lui faire tenir un objet pratique.\p"
	.string "Qu'est-ce qui lui conviendrait ?$"

gText_ApprenticeHoldNothing15::
	.string "C'est mieux s'il ne tient rien ?\n"
	.string "Tu en es sûr ?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Je vois. Dans ce cas, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "Reviens me voir !$"

gText_ApprenticeThanksHeldItem15::
	.string "Un {STR_VAR_1} ?\n"
	.string "Tu en es sûr ?\p"
	.string "Je vois. Dans ce cas, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "J'espère que mon POKéMON saura\n"
	.string "bien s'en servir.\p"
	.string "Reviens me voir !$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Non, non, attends une minute.\n"
	.string "Je crois que tu me l'as déjà dit.\p"
	.string "J'aimerais que tu me conseilles\n"
	.string "autre chose cette fois.\p"
	.string "Ou bien tu suggères que\n"
	.string "{STR_VAR_2} ne doit rien tenir ?\l"
	.string "Tu en es sûr ?$"

gText_ApprenticeWhichMonFirst0::
	.string "Ouaah, {PLAYER} !\n"
	.string "J'ai un dilemme, snif…\p"
	.string "Je veux commencer à combattre\l"
	.string "d'autres gens,\n"
	.string "mais je sais pas quoi faire.\p"
	.string "Comment je dois placer mes POKéMON\n"
	.string "pour qu'ils soient au plus fort ?\p"
	.string "Dis-moi, {PLAYER}.\n"
	.string "Si tu étais moi, lequel\l"
	.string "de ces POKéMON\l"
	.string "tu enverrais en premier ?$"

gText_ApprenticeMonFirstThanks0::
	.string "Mon {STR_VAR_1} doit commencer ?\n"
	.string "Ouaaaah !\p"
	.string "Oh ! Désolé !\n"
	.string "Tu m'as rendu heureux\l"
	.string "en choisissant mon premier\l"
	.string "POKéMON, et ça me fait pleurer…\p"
	.string "Merci beaucoup !$"

gText_ApprenticeWhichMonFirst1::
	.string "Oui ! C'est {PLAYER} !\n"
	.string "Super ! Je voulais te demander un truc !\p"
	.string "Euh, parmi mes POKéMON,\l"
	.string "lequel tu penses\n"
	.string "que je dois envoyer en premier ?$"

gText_ApprenticeMonFirstThanks1::
	.string "Mon {STR_VAR_1} ? C'est vrai.\n"
	.string "D'accord, je vais faire ça !\p"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, salut !\p"
	.string "Je pense qu'en combat,\l"
	.string "c'est très important\n"
	.string "de savoir quel POKéMON sort en premier.\p"
	.string "Parmi les POKéMON que j'ai,\n"
	.string "lequel serait bien à envoyer en premier ?$"

gText_ApprenticeMonFirstThanks2::
	.string "Mon {STR_VAR_1} commence ?\n"
	.string "D'accord, j'ai compris !\p"
	.string "À la prochaine !$"

gText_ApprenticeWhichMonFirst3::
	.string "Salut, {PLAYER}…\n"
	.string "Désolé de te déranger encore avec\l"
	.string "une autre question.\p"
	.string "J'ai si peu confiance en moi, je ne sais\n"
	.string "pas quoi faire sans toi, {PLAYER}.\p"
	.string "C'est peut-être une perte\l"
	.string "de temps d'y penser,\n"
	.string "mais j'arrive pas à décider…\l"
	.string "\p"
	.string "Lequel de mes POKéMON je dois envoyer\n"
	.string "en premier en combat ?$"

gText_ApprenticeMonFirstThanks3::
	.string "Mon {STR_VAR_1} ?\n"
	.string "Compris !\p"
	.string "J'arrive pas à croire que\l"
	.string "tu prennes le temps\n"
	.string "de répondre si souvent à mes questions !\p"
	.string "Je suis tellement reconnaissant que tu me\n"
	.string "parles… Merci !$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN} ! C'est moi !\n"
	.string "Je suis content de te voir, j'ai\l"
	.string "un petit problème.\p"
	.string "J'arrive pas à décider\l"
	.string "l'ordre de mes POKéMON.\n"
	.string "Tu peux décider pour moi ?\p"
	.string "Oh, pas besoin de décider\l"
	.string "toute l'équipe\n"
	.string "maintenant.\p"
	.string "Tu peux décider juste du premier\n"
	.string "POKéMON ?$"

gText_ApprenticeMonFirstThanks4::
	.string "Mon {STR_VAR_1} ? Super !\p"
	.string "En sachant que c'est toi\l"
	.string "qui as décidé, {PLAYER}{KUN},\l"
	.string "je serai moins triste si je perds.\p"
	.string "Bon, je reviendrai te demander conseil.\n"
	.string "Salut !$"

gText_ApprenticeWhichMonFirst5::
	.string "Salut, mon prof {PLAYER}{KUN} !\n"
	.string "Je suis encore débordé aujourd'hui !\p"
	.string "Je dois faire du vélo, faire les courses,\n"
	.string "et fredonner.\p"
	.string "J'ai même pas eu le temps de décider\n"
	.string "l'ordre de mon équipe POKéMON.\p"
	.string "Alors, tu peux jeter\l"
	.string "un œil à mon équipe ?\n"
	.string "Lequel doit commencer ?$"

gText_ApprenticeMonFirstThanks5::
	.string "OK, compris.\n"
	.string "J'ai au moins le temps de mettre\l"
	.string "{STR_VAR_1} en tête !\p"
	.string "Oups, ma copine m'attend !\n"
	.string "Merci ! À plus !$"

gText_ApprenticeWhichMonFirst6::
	.string "Youhou ! Salut, {PLAYER} !\n"
	.string "Tu te balades toujours avec un air dur !\p"
	.string "Écoute, j'ai encore besoin de toi !\n"
	.string "C'est comme d'habitude !\p"
	.string "Roulement de tambour !\n"
	.string "Ma question concerne mon équipe.\p"
	.string "Lequel de mes POKéMON\l"
	.string "doit être le premier\n"
	.string "à sortir en combat ?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm !\n"
	.string "Tu dis {STR_VAR_1} !\l"
	.string "Merci pour cette réponse\l"
	.string "trop cool !\p"
	.string "Je crois que c'est tout\l"
	.string "ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeWhichMonFirst7::
	.string "Merci beaucoup de t'arrêter pour\n"
	.string "me parler, {PLAYER}.\p"
	.string "Je sais que j'abuse\l"
	.string "un peu de ta gentillesse,\n"
	.string "mais puis-je te demander conseil ?\p"
	.string "J'aimerais que tu décides de l'ordre\n"
	.string "de mon équipe POKéMON.\p"
	.string "Ça me ferait plaisir si\l"
	.string "tu pouvais décider quel\l"
	.string "POKéMON doit passer en premier.$"

gText_ApprenticeMonFirstThanks7::
	.string "Donc {STR_VAR_1} !\n"
	.string "Je le mets en premier tout de suite !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter\l"
	.string "sur toi encore.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeWhichMonFirst8::
	.string "Aïe ! {PLAYER} !\n"
	.string "Je… je suis trop content de te revoir !\p"
	.string "Mes POKéMON sont devenus\n"
	.string "beaucoup plus forts !\p"
	.string "Mais je ne gagne pas toujours.\l"
	.string "On dirait que\n"
	.string "ça dépend du POKéMON qui commence.\p"
	.string "{PLAYER}, s'il te plaît,\l"
	.string "j'ai besoin de ton aide !\p"
	.string "Décide lequel de mes POKéMON\n"
	.string "doit sortir en premier !$"

gText_ApprenticeMonFirstThanks8::
	.string "Soupir… Je suis submergé de bonheur…\p"
	.string "C'est comme un rêve que tu décides\n"
	.string "pour moi, {PLAYER}.\p"
	.string "Mais parfaitement compris !\n"
	.string "Je vais commencer avec {STR_VAR_1} !\p"
	.string "J'espère que tu voudras\l"
	.string "encore m'apprendre\n"
	.string "des choses une autre fois.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hello, hello !\n"
	.string "Mon mentor, {PLAYER}{KUN} !\l"
	.string "Balance tes sages conseils aujourd'hui !\p"
	.string "Tu vois, j'ai monté une équipe de\n"
	.string "trois POKéMON. Ça va.\p"
	.string "Mais l'ordre de combat de l'équipe\n"
	.string "n'est pas décidé.\p"
	.string "C'est là que tu interviens, {PLAYER}{KUN} !\n"
	.string "Décide quel POKéMON commence !\p"
	.string "Ne sois pas timide.\n"
	.string "Balance !$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, c'est {STR_VAR_1}\l"
	.string "qui commence !\n"
	.string "OK, OK !\l"
	.string "Je réorganise l'équipe, wham !\p"
	.string "Bon, merci, comme toujours !\n"
	.string "Adios !$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, écoute !\n"
	.string "C'est la crise !\p"
	.string "Mes trois POKéMON entrent\n"
	.string "en combat en même temps !\p"
	.string "Bien sûr que c'est impossible !\n"
	.string "Wahahaha !\p"
	.string "Mais ça, c'est vrai.\n"
	.string "Je suis pas très bon pour décider\l"
	.string "l'ordre de mes POKéMON.\p"
	.string "Alors, tu peux décider\l"
	.string "pour moi quel\n"
	.string "POKéMON doit commencer, maître ?$"

gText_ApprenticeMonFirstThanks10::
	.string "D'accord, donc tu choisis\l"
	.string "{STR_VAR_1} ?\n"
	.string "Je ferai commencer\l"
	.string "n'importe qui sauf lui !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu\l"
	.string "continueras à m'apprendre !$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y !\n"
	.string "Ça se lit “ahoy” !\p"
	.string "Le MARIN rappeur, c'est moi !\n"
	.string "J'te pose une question\l"
	.string "trop stylée, ma foi !\p"
	.string "C'est une question\l"
	.string "d'ordre d'équipe\n"
	.string "et j'attends ta suggestion !\p"
	.string "Parmi tout ça,\l"
	.string "lequel doit commencer,\n"
	.string "le premier sur le champ ?$"

gText_ApprenticeMonFirstThanks11::
	.string "OK, je t'entends, c'est clair !\n"
	.string "Je vais changer l'ordre, c'est sûr !\p"
	.string "Si j'ai besoin d'un conseil,\n"
	.string "{PLAYER}, j'écouterai\l"
	.string "toujours tes paroles !$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER} !\n"
	.string "Comment tu vas ?\p"
	.string "Je fais quoi ?\l"
	.string "Je te pose ma question ?\n"
	.string "Uh-huh, j'ai un truc à demander !\l"
	.string "Tu m'entends bien ?\l"
	.string "Tu m'entends bien !\p"
	.string "Tu dois décider lequel de mes\n"
	.string "POKéMON doit être le premier !\l"
	.string "En combat, je veux dire.$"

gText_ApprenticeMonFirstThanks12::
	.string "Mon {STR_VAR_1} ? Oui !\n"
	.string "Ça me va, pas de souci !\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof… aïe… {PLAYER}{KUN}…\n"
	.string "J'ai mal au ventre d'un coup…\p"
	.string "…Ça va mieux maintenant…\p"
	.string "Je crois que je me suis rendu malade\n"
	.string "à force de réfléchir à l'ordre\l"
	.string "de mes POKéMON.\p"
	.string "Donc, vu la situation,\n"
	.string "j'ai besoin que tu décides pour moi.\p"
	.string "{PLAYER}{KUN}, lequel\l"
	.string "de mes POKéMON doit\n"
	.string "commencer ? Pour que je\l"
	.string "gagne, quoi.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hmm, d'accord.\n"
	.string "{STR_VAR_1} commence.\p"
	.string "Je réglerai l'ordre comme ça après\n"
	.string "avoir mangé.\p"
	.string "J'espère pouvoir continuer\l"
	.string "à te demander\n"
	.string "de l'aide comme ça.$"

gText_ApprenticeWhichMonFirst14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN} ?\p"
	.string "S'il te plaît, ne me\l"
	.string "regarde pas comme ça.\n"
	.string "Ça me gêne énormément.\p"
	.string "Euh…\n"
	.string "J'ai vraiment besoin de tes conseils.\p"
	.string "C'est gênant à dire,\n"
	.string "mais j'ai choisi mon\l"
	.string "équipe de 3 POKéMON.\l"
	.string "Mais je n'arrive pas à décider l'ordre.\p"
	.string "Quel POKéMON je dois\l"
	.string "envoyer en premier\n"
	.string "pour au moins avoir\l"
	.string "l'air capable ?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais commencer avec {STR_VAR_1}.\p"
	.string "J'espère faire de mon mieux\n"
	.string "sans être trop gêné.\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit,\l"
	.string "j'espère que tu seras\l"
	.string "encore aussi serviable.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hmm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais est-ce bien vrai ?\l"
	.string "Un sosie, peut-être ?\p"
	.string "Oh, non, non, non,\l"
	.string "ne t'inquiète pas !\n"
	.string "Si tu es vraiment {PLAYER},\l"
	.string "oublie mon impolitesse.\p"
	.string "Ce que je veux, c'est ton avis.\p"
	.string "Voici mon équipe POKéMON.\n"
	.string "Je voudrais que tu me dises lequel\l"
	.string "doit commencer en combat.$"

gText_ApprenticeMonFirstThanks15::
	.string "Mon {STR_VAR_1}…\n"
	.string "Tu te moques pas de moi ?\p"
	.string "Je vois. Dans ce cas, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "Je suis comme tu vois,\l"
	.string "mais je ferai\n"
	.string "de mon mieux.\p"
	.string "Reviens me voir !$"

gText_ApprenticeWhichMon0::
	.string "Snif…\n"
	.string "Oh, {PLAYER} !\p"
	.string "Quel timing parfait !\n"
	.string "Y a un truc que j'arrive pas à décider…\p"
	.string "J'arrive pas à décider quel POKéMON\n"
	.string "je dois utiliser.\p"
	.string "J'hésite entre les POKéMON\n"
	.string "{STR_VAR_1} et\l"
	.string "{STR_VAR_2}…\p"
	.string "{PLAYER}, lequel\l"
	.string "me donnerait une chance\n"
	.string "de gagner, même à moi ?$"

gText_ApprenticeMonThanks0::
	.string "Snif… J… je comprends !\n"
	.string "Oh ! Désolé !\l"
	.string "Tu me rends si heureux que je pleure…\p"
	.string "Je vais faire de mon mieux pour attraper\n"
	.string "un {STR_VAR_1} !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeWhichMon1::
	.string "Oui ! C'est {PLAYER} !\n"
	.string "Oui, tu arrives au bon moment !\l"
	.string "J'ai encore besoin de tes conseils !\p"
	.string "Euh, je suis perdu…\l"
	.string "Je dois utiliser\n"
	.string "{STR_VAR_1} ou {STR_VAR_2}…\p"
	.string "Lequel tu penses\l"
	.string "que je dois élever,\n"
	.string "{PLAYER} ?$"

gText_ApprenticeMonThanks1::
	.string "Oh, donc {STR_VAR_1} est mieux !\n"
	.string "D'accord, je vais faire ça !\p"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, salut !\n"
	.string "J'ai une question.\p"
	.string "J'hésite entre élever\n"
	.string "un {STR_VAR_1} ou {STR_VAR_2}.\p"
	.string "Quel POKéMON, à ton avis,\n"
	.string "sera le plus fort ?$"

gText_ApprenticeMonThanks2::
	.string "Tu choisis {STR_VAR_1} ?\n"
	.string "D'accord, compris !\p"
	.string "Je vais tout de suite attraper\n"
	.string "un {STR_VAR_1} puissant !\p"
	.string "À la prochaine !$"

gText_ApprenticeWhichMon3::
	.string "Salut, {PLAYER}…\p"
	.string "Euh, tu as sûrement déjà oublié\n"
	.string "quelqu'un comme moi…\p"
	.string "…Mais si tu pouvais me conseiller…\p"
	.string "J'arrive pas à décider quel type de\n"
	.string "POKéMON je dois élever…\p"
	.string "J'ai réduit le choix aux POKéMON\n"
	.string "{STR_VAR_1} et\l"
	.string "{STR_VAR_2}, mais c'est\l"
	.string "là que je bloque…\p"
	.string "{PLAYER}, tu n'as sûrement pas envie,\n"
	.string "mais s'il te plaît, décide pour moi.$"

gText_ApprenticeMonThanks3::
	.string "Mais est-ce qu'un {STR_VAR_1} sauvage\n"
	.string "m'écoutera seulement ?\p"
	.string "Je vais essayer !\p"
	.string "Mais est-ce que je pourrai en attraper un…\n"
	.string "Non ! Je vais faire de mon mieux !\p"
	.string "Merci !$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN} !\l"
	.string "Je suis trop content\l"
	.string "de te voir !\n"
	.string "J'allais justement te chercher !\p"
	.string "Tu peux décider quel POKéMON\n"
	.string "je dois utiliser ?\p"
	.string "Par exemple…\n"
	.string "Que dirais-tu des\l"
	.string "POKéMON {STR_VAR_1}\l"
	.string "et {STR_VAR_2} ?\p"
	.string "Lequel tu penses qui serait\n"
	.string "mieux ?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1} ? Super !\p"
	.string "En sachant que c'est toi\l"
	.string "qui as décidé, {PLAYER}{KUN},\l"
	.string "je serai moins triste si je perds.\p"
	.string "Bon, je reviendrai te demander conseil.\n"
	.string "Salut !$"

gText_ApprenticeWhichMon5::
	.string "Si c'est pas {PLAYER}{KUN} !\l"
	.string "Ça va ?\n"
	.string "Je suis encore débordé, comme toujours !\p"
	.string "Je veux assurer avec les POKéMON aussi,\n"
	.string "mais j'arrive pas à décider\l"
	.string "quel POKéMON utiliser.\p"
	.string "Tu vois comme\l"
	.string "{STR_VAR_1} a l'air fort ?\n"
	.string "Mais {STR_VAR_2}, c'est dur d'ignorer.\p"
	.string "{PLAYER}{KUN}, donne-moi\l"
	.string "un bon conseil !\n"
	.string "Lequel serait bien pour moi ?$"

gText_ApprenticeMonThanks5::
	.string "OK, compris.\n"
	.string "Je vais trouver le temps pour attraper\l"
	.string "le {STR_VAR_1}\l"
	.string "que tu as conseillé.\p"
	.string "Je suis content d'avoir un bon mentor.\n"
	.string "Merci ! À plus !$"

gText_ApprenticeWhichMon6::
	.string "Oh !\n"
	.string "Oui, c'est {PLAYER} !\p"
	.string "J'ai pas perdu de temps\l"
	.string "à me vanter\n"
	.string "auprès de mes amis de t'avoir rencontré !\p"
	.string "J'ai encore besoin de ton cerveau.\n"
	.string "Pour toi, c'est facile !\p"
	.string "Roulement de tambour !\n"
	.string "Ma question, c'est…\p"
	.string "Si je devais élever un POKéMON,\n"
	.string "et que le choix était {STR_VAR_1}\l"
	.string "ou {STR_VAR_2}, lequel je dois prendre ?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh !\n"
	.string "Tu dis {STR_VAR_1} !\l"
	.string "Merci pour cette réponse\l"
	.string "trop cool !\p"
	.string "Je crois que c'est tout\l"
	.string "ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeWhichMon7::
	.string "Oh, c'est toi, {PLAYER} ?\n"
	.string "Je suis ravi de te revoir !\p"
	.string "Depuis que je suis ton apprenti,\n"
	.string "ma confiance a grandi.\p"
	.string "Je crois que je suis prêt à élever\n"
	.string "mon propre POKéMON !\p"
	.string "{PLAYER}, tu peux choisir\l"
	.string "quel POKéMON\n"
	.string "je dois élever ?\p"
	.string "Le choix est entre les POKéMON\n"
	.string "{STR_VAR_1} ou {STR_VAR_2}…\l"
	.string "Lequel est fait pour moi ?$"

gText_ApprenticeMonThanks7::
	.string "Donc {STR_VAR_1} !\n"
	.string "Je vais en trouver un tout de suite !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter\l"
	.string "sur toi encore.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeWhichMon8::
	.string "Aïe ! {PLAYER} ! Je te revois !\n"
	.string "Je… je suis trop content !\p"
	.string "Oh-oh-oh, je sais !\n"
	.string "Je dois pas laisser passer cette chance !\p"
	.string "Je peux te demander\l"
	.string "un énorme service, {PLAYER} ?\n"
	.string "Choisis un POKéMON pour moi !\p"
	.string "Décide lequel est mieux,\l"
	.string "{STR_VAR_1} ou\l"
	.string "{STR_VAR_2} !$"

gText_ApprenticeMonThanks8::
	.string "Wouah ! Tu as décidé pour moi !\n"
	.string "Je vais élever {STR_VAR_1}\l"
	.string "du mieux que je peux.\p"
	.string "J'espère que tu voudras\l"
	.string "encore m'apprendre\n"
	.string "des choses une autre fois.$"

gText_ApprenticeWhichMon9::
	.string "Hé, hé !\n"
	.string "Mon mentor, {PLAYER}{KUN} !\p"
	.string "Salut, je te cherchais\n"
	.string "pour encore tes sages conseils !\p"
	.string "Quel POKéMON serait fait\n"
	.string "pour moi, {STR_VAR_1}\l"
	.string "ou {STR_VAR_2} ?\p"
	.string "Ne sois pas timide.\n"
	.string "Balance !$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, donc {STR_VAR_1} !\n"
	.string "OK, OK !\l"
	.string "J'en attrape un dans une BALL, cram !\p"
	.string "Bon, merci, comme toujours !\n"
	.string "Adios !$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, écoute !\l"
	.string "Grande nouvelle !\n"
	.string "J'ai attrapé un POKéMON mirage !\p"
	.string "Bien sûr que je mens !\n"
	.string "Wahahaha !\p"
	.string "Mais ça, c'est vrai.\n"
	.string "Je suis pas très bon pour attraper\l"
	.string "des POKéMON.\p"
	.string "Alors, tu peux décider\l"
	.string "pour moi quel\n"
	.string "type de POKéMON je dois attraper,\l"
	.string "maître ?\p"
	.string "Lequel serait mieux ?\n"
	.string "{STR_VAR_1} ou {STR_VAR_2} ?$"

gText_ApprenticeMonThanks10::
	.string "D'accord, donc tu choisis\l"
	.string "{STR_VAR_1} ?\n"
	.string "Alors je vais attraper l'autre !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu\l"
	.string "continueras à m'apprendre !$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y !\n"
	.string "Ça se lit “ahoy” !\p"
	.string "Le MARIN rappeur, c'est moi !\n"
	.string "Tu te souviens sûrement de moi ?\p"
	.string "Aujourd'hui j'ai une question POKéMON\n"
	.string "et j'attends ta suggestion !\p"
	.string "J'hésite entre\n"
	.string "{STR_VAR_1} et {STR_VAR_2}, tu vois.\l"
	.string "Lequel je dois attraper, dis ?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, tu dis, hé, hé !\n"
	.string "J'vais en attraper un sans tarder !\p"
	.string "Si j'ai besoin d'un conseil,\n"
	.string "{PLAYER}, j'écouterai\l"
	.string "toujours tes paroles !$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, mais c'est {PLAYER} !\p"
	.string "Je fais quoi ?\l"
	.string "Je te demande conseil ?\n"
	.string "Pourquoi pas ? Je te parle déjà !\p"
	.string "Ça fait longtemps.\l"
	.string "Brisons la glace.\n"
	.string "Moi aussi, je cherche des conseils !\l"
	.string "Tu me reçois ?\l"
	.string "Tu me reçois !\p"
	.string "Mes POKéMON… Lequel je dois utiliser ?\n"
	.string "J'hésite entre\l"
	.string "{STR_VAR_1} et {STR_VAR_2}.\l"
	.string "Tu choisis lequel ?$"

gText_ApprenticeMonThanks12::
	.string "Si {STR_VAR_1} est le meilleur,\n"
	.string "je ferai comme tu suggères !\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeWhichMon13::
	.string "Oh, salut, {PLAYER}{KUN}…\n"
	.string "J'ai un mal de crâne horrible…\p"
	.string "J'ai dû trop m'inquiéter au sujet\n"
	.string "du POKéMON que je devrais élever.\p"
	.string "Donc, vu la situation,\n"
	.string "j'ai besoin que tu décides pour moi.\p"
	.string "{PLAYER}{KUN}, si je\l"
	.string "dois choisir entre\n"
	.string "les POKéMON {STR_VAR_1} et\l"
	.string "{STR_VAR_2}, lequel je dois prendre ?$"

gText_ApprenticeMonThanks13::
	.string "Hmm, donc {STR_VAR_1}, d'accord.\n"
	.string "J'irai en chercher un quand ça ira mieux.\p"
	.string "J'espère pouvoir continuer\l"
	.string "à te demander\n"
	.string "de l'aide comme ça.$"

gText_ApprenticeWhichMon14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}… ?\p"
	.string "S'il te plaît, ne me\l"
	.string "regarde pas comme ça.\n"
	.string "Ça me gêne énormément…\l"
	.string "Je… j'ai besoin de tes conseils.\p"
	.string "Je… c'est vraiment gênant,\l"
	.string "mais je n'arrive pas\n"
	.string "à décider quel POKéMON utiliser.\p"
	.string "Si le choix est {STR_VAR_1} ou\n"
	.string "{STR_VAR_2}, lequel est mieux ?$"

gText_ApprenticeMonThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais faire de mon mieux\l"
	.string "avec {STR_VAR_1}.\p"
	.string "J'espère faire de mon mieux\n"
	.string "sans être trop gêné.\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit,\l"
	.string "j'espère que tu seras\l"
	.string "encore aussi serviable.$"

gText_ApprenticeWhichMon15::
	.string "Hmm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais es-tu bien réel ?\p"
	.string "Non, non, si tu es réel, c'est très bien.\n"
	.string "D'ailleurs, j'aimerais obtenir\l"
	.string "ton avis.\p"
	.string "C'est à propos du POKéMON\l"
	.string "que je dois utiliser.\p"
	.string "Si le choix est entre les POKéMON\n"
	.string "{STR_VAR_1} et {STR_VAR_2}, lequel est\l"
	.string "le plus digne de moi ?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1} ?\n"
	.string "Es-tu certain ?\p"
	.string "Je vois. Dans ce cas, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "J'espère que c'est quelque\l"
	.string "chose que même moi,\n"
	.string "je pourrai gérer avec brio.\p"
	.string "Revenons nous voir !$"

gText_ApprenticeWhichMove0::
	.string "Waaah ! Oh, {PLAYER} !\n"
	.string "Snif… Hic…\p"
	.string "J'ai un dilemme !\n"
	.string "J'arrive pas à choisir une attaque pour\l"
	.string "mon {STR_VAR_1}…\p"
	.string "S'il te plaît, s'il te\l"
	.string "plaît, {PLAYER}.\n"
	.string "Tu peux décider pour moi ?\p"
	.string "Pour mon {STR_VAR_1},\l"
	.string "quelle attaque serait\n"
	.string "la meilleure : {STR_VAR_2}\l"
	.string "ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1} ?\n"
	.string "Waaaaah !\p"
	.string "Oh ! Désolé, {PLAYER} !\n"
	.string "Tu me rends si heureux en choisissant\l"
	.string "l'attaque… J'en pleure…\p"
	.string "Snif…\n"
	.string "Merci beaucoup !$"

gText_ApprenticeWhichMove1::
	.string "Oui ! Salut, {PLAYER} !\n"
	.string "J'ai encore besoin de tes conseils !\p"
	.string "Je veux apprendre à mon {STR_VAR_1}\n"
	.string "une attaque trop cool.\p"
	.string "J'aime bien ces deux attaques :\n"
	.string "{STR_VAR_2} ou {STR_VAR_3}.\l"
	.string "Tu me conseilles laquelle ?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} est mieux ? Je crois aussi !\n"
	.string "D'accord, je vais choisir ça !\p"
	.string "Si on se revoit ici,\l"
	.string "apprends-moi encore\n"
	.string "des trucs, maître !$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, salut !\n"
	.string "C'est à propos de mon {STR_VAR_1}, mais je\l"
	.string "m'inquiète pour ses attaques.\p"
	.string "Tu vois, c'est entre {STR_VAR_2}\n"
	.string "et {STR_VAR_3}.\p"
	.string "Laquelle est plus forte\l"
	.string "et meilleure pour\n"
	.string "mon {STR_VAR_1} ?$"

gText_ApprenticeMoveThanks2::
	.string "Tu choisis {STR_VAR_1} ?\n"
	.string "D'accord, compris !\p"
	.string "Je vais apprendre {STR_VAR_1} à\n"
	.string "mon POKéMON tout de suite !\p"
	.string "À la prochaine !$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "Je suis désespéré, vraiment !\p"
	.string "J'ai décidé d'élever un POKéMON,\n"
	.string "mais maintenant je n'arrive même pas à\l"
	.string "décider quelle attaque lui apprendre…\p"
	.string "Je sais que ça ne veut rien dire\n"
	.string "pour toi, {PLAYER}.\p"
	.string "Mais pour moi, ça compte beaucoup…\p"
	.string "S'il te plaît, {PLAYER},\l"
	.string "tu peux choisir\n"
	.string "une attaque pour mon {STR_VAR_1} ?\p"
	.string "Si tu pouvais choisir entre\n"
	.string "{STR_VAR_2} et {STR_VAR_3}…$"
gText_ApprenticeMoveThanks3::
	.string "Je comprends !\p"
	.string "Mais est-ce qu'il voudra apprendre\n"
	.string "{STR_VAR_1} pour moi…\l"
	.string "Non ! Je vais faire de mon mieux !\p"
	.string "Merci !$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN} !\n"
	.string "Moi aussi, j'espérais te voir !\p"
	.string "Je me demandais quelle attaque\n"
	.string "conviendrait à mon {STR_VAR_1}.\p"
	.string "J'arrive pas à choisir, alors tu peux\n"
	.string "décider pour moi ?\p"
	.string "Par exemple… entre les attaques\n"
	.string "{STR_VAR_2} et {STR_VAR_3} ?\l"
	.string "Laquelle est mieux ?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1} ? Super !\p"
	.string "En sachant que c'est toi\l"
	.string "qui as décidé, {PLAYER}{KUN},\l"
	.string "je serai moins triste si je perds.\p"
	.string "Bon, je reviendrai te demander conseil.\n"
	.string "Salut !$"

gText_ApprenticeWhichMove5::
	.string "Comment ça peut être aussi chargé ?\n"
	.string "Hé, si c'est pas {PLAYER}{KUN} !\l"
	.string "Ça va ?\p"
	.string "Depuis ce matin, j'ai fait\n"
	.string "mon jogging, ma natation et la cuisine !\p"
	.string "Tu n'imagines pas\l"
	.string "comme je suis occupé !\p"
	.string "J'arrive même pas à décider quelle attaque\n"
	.string "mon {STR_VAR_1} doit apprendre !\p"
	.string "{STR_VAR_2} a l'air bien, hein ?\n"
	.string "Mais {STR_VAR_3} est pas mal non plus.\p"
	.string "{PLAYER}{KUN}, donne-moi\l"
	.string "un bon conseil !\n"
	.string "Quelle attaque serait bien pour moi ?$"

gText_ApprenticeMoveThanks5::
	.string "OK, compris.\n"
	.string "Je vais me libérer du temps et\l"
	.string "apprendre cette attaque.\p"
	.string "Je suis content d'avoir un bon mentor.\n"
	.string "Merci ! À plus !$"

gText_ApprenticeWhichMove6::
	.string "Oh ! Quelle chance !\n"
	.string "Je te revois, {PLAYER} !\l"
	.string "J'ai encore besoin\l"
	.string "de ton cerveau aujourd'hui.\p"
	.string "Roulement de tambour !\n"
	.string "Ma question, c'est…\p"
	.string "Pour mon {STR_VAR_1}, quelle attaque est\n"
	.string "la plus adaptée, {STR_VAR_2} ou\l"
	.string "{STR_VAR_3} ?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh !\n"
	.string "Tu dis {STR_VAR_1} !\l"
	.string "Merci pour cette réponse\l"
	.string "trop cool !\p"
	.string "Je crois que c'est tout\l"
	.string "ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeWhichMove7::
	.string "Oh, bonjour, {PLAYER}.\n"
	.string "J'espère que tu vas bien ?\p"
	.string "Je dois encore te demander conseil.\n"
	.string "C'est à propos de mon cher {STR_VAR_1}.\p"
	.string "Quelle serait l'attaque idéale pour\n"
	.string "mon adorable {STR_VAR_1} ?\l"
	.string "{STR_VAR_2} ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks7::
	.string "Donc {STR_VAR_1} !\n"
	.string "Je vais l'apprendre tout de suite !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter\l"
	.string "sur toi encore.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeWhichMove8::
	.string "Aïe ! {PLAYER} ! Je te revois !\n"
	.string "Je… je suis trop content !\p"
	.string "Quand j'ai besoin d'aide,\l"
	.string "tu es toujours\n"
	.string "là pour moi, {PLAYER} !\p"
	.string "Aujourd'hui, je veux que tu me\n"
	.string "recommandes une attaque !\p"
	.string "S'il te plaît, choisis une attaque pour\n"
	.string "mon {STR_VAR_1} !\p"
	.string "Laquelle est mieux,\n"
	.string "{STR_VAR_2} ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh ! Merci !\n"
	.string "Donc {STR_VAR_1} !\l"
	.string "Parfaitement compris !\p"
	.string "J'espère que tu voudras\l"
	.string "encore m'apprendre\n"
	.string "des choses une autre fois.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN},\l"
	.string "bueno !\n"
	.string "J'espère encore profiter de\l"
	.string "tes sages conseils aujourd'hui !\p"
	.string "Quelle serait la\l"
	.string "meilleure attaque pour\n"
	.string "mon {STR_VAR_1} ?\p"
	.string "Il me faut un truc\n"
	.string "qui me fera gagner\l"
	.string "d'un coup !\p"
	.string "Ce serait {STR_VAR_2} ?\n"
	.string "Ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, donc {STR_VAR_1} !\n"
	.string "Si, bueno !\l"
	.string "Je vais l'apprendre, ka-blam !\p"
	.string "Bon, merci, comme toujours !\n"
	.string "Adios !$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, c'est\l"
	.string "complètement dingue !\p"
	.string "Mon POKéMON !\n"
	.string "Il a appris six attaques !\p"
	.string "Bien sûr que je mens !\n"
	.string "Wahahaha !\p"
	.string "Mais ça, c'est vrai.\n"
	.string "Je suis pas très bon\l"
	.string "pour choisir des attaques\l"
	.string "pour mes POKéMON.\p"
	.string "Alors, tu peux décider\l"
	.string "pour moi quelle\n"
	.string "attaque je dois lui apprendre ?\p"
	.string "{STR_VAR_2} ou {STR_VAR_3}…\l"
	.string "Laquelle\n"
	.string "va le mieux avec mon\l"
	.string "{STR_VAR_1} ?$"

gText_ApprenticeMoveThanks10::
	.string "D'accord, donc tu choisis\l"
	.string "{STR_VAR_1} ?\n"
	.string "Alors je vais prendre une autre attaque !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu\l"
	.string "continueras à m'apprendre !$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y !\n"
	.string "Ça se lit “ahoy” !\p"
	.string "Le MARIN rappeur, c'est moi !\n"
	.string "Toujours dans le flow,\l"
	.string "je sais pas pourquoi.\p"
	.string "Aujourd'hui j'ai une question d'attaque\n"
	.string "et j'attends ta suggestion !\p"
	.string "{STR_VAR_2} et {STR_VAR_3},\n"
	.string "c'est les attaques. Laquelle\l"
	.string "est la meilleure pour mon\l"
	.string "{STR_VAR_1} pour qu'il groove ?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, tu dis, hé, hé !\n"
	.string "J'vais lui apprendre sans tarder !\p"
	.string "Si j'ai besoin d'un conseil,\n"
	.string "{PLAYER}, j'écouterai\l"
	.string "toujours tes paroles !$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeahah, mais c'est {PLAYER} !\p"
	.string "Je fais quoi ?\l"
	.string "Je te demande conseil ?\n"
	.string "Pourquoi pas ? Je te parle déjà !\p"
	.string "{PLAYER}, je te surprends ?\n"
	.string "J'veux ton avis, tu vois pas ?\p"
	.string "Tu me reçois ?\n"
	.string "Tu me reçois !\p"
	.string "Mon {STR_VAR_1}…\l"
	.string "Quelle attaque utiliser ?\n"
	.string "{STR_VAR_2} ou {STR_VAR_3},\l"
	.string "tu choisis laquelle ?$"

gText_ApprenticeMoveThanks12::
	.string "Si {STR_VAR_1} est la meilleure,\n"
	.string "je ferai comme tu suggères !\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeWhichMove13::
	.string "Gahack ! Gah ! Oh, {PLAYER}{KUN}…\n"
	.string "J'ai un sale rhume…\p"
	.string "Je veux choisir une attaque pour mon POKéMON,\n"
	.string "mais je n'y arrive pas…\p"
	.string "Donc, vu la situation,\n"
	.string "j'ai besoin que tu décides pour moi.\p"
	.string "{PLAYER}{KUN}, si je\l"
	.string "dois choisir entre\n"
	.string "{STR_VAR_2} et {STR_VAR_3} pour\l"
	.string "mon {STR_VAR_1}, laquelle est mieux ?$"

gText_ApprenticeMoveThanks13::
	.string "Hmm, {STR_VAR_1}, d'accord. Kof !\n"
	.string "Je l'apprendrai quand ça ira mieux.\p"
	.string "J'espère pouvoir continuer\l"
	.string "à te demander\n"
	.string "de l'aide comme ça.$"

gText_ApprenticeWhichMove14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}… ?\p"
	.string "S'il te plaît, ne me\l"
	.string "regarde pas comme ça.\n"
	.string "Ça me gêne énormément…\l"
	.string "Je… j'ai besoin de tes conseils.\p"
	.string "Je… c'est vraiment gênant,\l"
	.string "mais je n'arrive pas\n"
	.string "à décider quelle attaque apprendre\l"
	.string "à mon POKéMON.\p"
	.string "C'est pour mon {STR_VAR_1}.\n"
	.string "Si le choix est {STR_VAR_2} ou\l"
	.string "{STR_VAR_3}, laquelle est mieux ?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais essayer {STR_VAR_1}.\p"
	.string "J'espère que j'arriverai à lui apprendre…\n"
	.string "Ça me stresse tellement…\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit,\l"
	.string "j'espère que tu seras\l"
	.string "encore aussi serviable.$"

gText_ApprenticeWhichMove15::
	.string "Hmm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais es-tu bien réel ?\p"
	.string "Serais-tu l'un de ces célèbres\n"
	.string "imitateurs ?\p"
	.string "Non, non, si tu es réel,\l"
	.string "c'est très bien.\n"
	.string "Pas besoin de t'énerver, je t'assure !\p"
	.string "D'ailleurs, j'aimerais obtenir\n"
	.string "ton avis.\p"
	.string "C'est à propos de mon {STR_VAR_1}.\p"
	.string "Quelle attaque serait mieux pour lui,\n"
	.string "{STR_VAR_2} ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1} ?\n"
	.string "Sans la moindre hésitation ?\p"
	.string "Je vois. Dans ce cas, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "J'espère que c'est quelque\l"
	.string "chose que même\n"
	.string "mon POKéMON pourra apprendre.\p"
	.string "Revenons nous voir !$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER} ?\n"
	.string "C'est {PLAYER} !\l"
	.string "Oh ! Snif… bouhou…\l"
	.string "Écoute, s'il te plaît !\p"
	.string "Moi… Quand je combats,\l"
	.string "je suis tellement nerveux\n"
	.string "que je me mets à pleurer\l"
	.string "même si je gagne…\p"
	.string "J'aimerais dire un truc stylé\n"
	.string "quand je gagne…\p"
	.string "S'il te plaît, s'il te plaît, {PLAYER} !\n"
	.string "Tu peux m'apprendre quelque chose\l"
	.string "de stylé à dire quand\l"
	.string "je gagne, pour pas\l"
	.string "pleurer ?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Génial ! Trop bien ! Awoooh !\n"
	.string "C'est vraiment stylé !\p"
	.string "Oh… Pardon…\n"
	.string "Je suis si heureux que je pleure…\p"
	.string "Snif… {PLAYER} !\n"
	.string "Merci pour tout !\p"
	.string "Je me battrai du mieux possible\n"
	.string "pour toi, {PLAYER} !\p"
	.string "{PLAYER}…\n"
	.string "La prochaine fois… on se battra !$"

gText_ApprenticePickWinSpeech1::
	.string "Oui ! C'est {PLAYER} !\l"
	.string "Salut !\n"
	.string "Je voulais te demander un truc !\p"
	.string "Je veux dire quelque chose de stylé\n"
	.string "quand je gagne un match.\p"
	.string "T'as une phrase cool\n"
	.string "à me recommander ?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wouah ! C'est trop stylé !\n"
	.string "OK, je dirai ça !\p"
	.string "Merci de m'avoir appris tout ça !\n"
	.string "Je vais faire de mon mieux\l"
	.string "où que j'aille, à partir\l"
	.string "de maintenant !\p"
	.string "Quand on se reverra, ce sera pour\n"
	.string "un combat !$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, salut !\p"
	.string "Mes POKéMON et moi,\l"
	.string "on est prêts à tout,\n"
	.string "sauf pour une chose.\p"
	.string "Je crois que ce serait bien d'avoir\n"
	.string "un truc à crier quand je gagne.\p"
	.string "Tu peux trouver quelque chose de bien\n"
	.string "à dire ?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Stylé !\n"
	.string "Je vais utiliser ça !\p"
	.string "Je vais aller me battre partout\n"
	.string "sur la route.\p"
	.string "Qui sait, je pourrai peut-être même\n"
	.string "t'affronter un jour, {PLAYER}.\p"
	.string "La prochaine fois, retrouvons-nous\n"
	.string "sur un terrain de combat !$"

gText_ApprenticePickWinSpeech3::
	.string "Salut, {PLAYER}…\n"
	.string "Désolé de te déranger,\l"
	.string "mais je suis désespéré…\p"
	.string "Même quand…\n"
	.string "Même quand je gagne, j'ai rien\l"
	.string "de spécial à dire…\p"
	.string "Je sais que ça ne veut rien dire\n"
	.string "pour toi, {PLAYER}.\p"
	.string "Mais pour moi, ça compte beaucoup…\p"
	.string "S'il te plaît, {PLAYER},\l"
	.string "qu'est-ce que\n"
	.string "je dois dire si je gagne un combat ?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "C'est inspiré…\p"
	.string "Euh… Est-ce que quelqu'un comme moi\n"
	.string "peut vraiment dire ça ?\p"
	.string "Non ! Je vais faire de mon mieux !\p"
	.string "{PLAYER}, merci beaucoup\l"
	.string "de m'avoir\n"
	.string "supporté si longtemps…\p"
	.string "Je te promets de faire\l"
	.string "de mon mieux désormais.\p"
	.string "Je suis sûr que tu m'oublieras vite,\n"
	.string "mais retrouvons-nous\l"
	.string "quelque part !$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Y a quelque chose que\l"
	.string "je veux que tu entendes.\p"
	.string "Je sais que je n'ai pas toujours l'air\n"
	.string "gentil ou poli…\p"
	.string "Quand je gagne un combat, je crois\n"
	.string "que j'ai l'air arrogant.\p"
	.string "Je veux pas que les gens me détestent,\n"
	.string "alors je veux dire quelque chose de sympa\l"
	.string "à la personne que je bats.\p"
	.string "Mais je trouve rien de bien !\n"
	.string "Tu peux trouver un truc pour moi ?$"
gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Pas mal !\n"
	.string "Ouais, je vais dire ça !\p"
	.string "Je vais prendre la route et faire ce que\n"
	.string "je peux avec ce que\l"
	.string "tu m'as appris\l"
	.string "dans la tête et dans le cœur.\p"
	.string "Désolé d'avoir été si insistant\n"
	.string "avec toi !\p"
	.string "La prochaine fois, on se bat, d'accord ?\n"
	.string "À plus !$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, je n'en reviens pas\l"
	.string "comme je suis occupé !\n"
	.string "Oh, hé, je te cherchais,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Tu vas bien, comme d'habitude ?\n"
	.string "Moi, rien n'a changé.\p"
	.string "J'ai de la course,\l"
	.string "du combat et de la carto\n"
	.string "à faire. Pourquoi je suis si occupé ?\p"
	.string "Mais même si je suis occupé,\l"
	.string "ce serait impoli\n"
	.string "de faire demi-tour et partir\l"
	.string "après une victoire sans rien dire.\p"
	.string "Alors, ce serait quoi une phrase stylée\n"
	.string "pour montrer mon style\l"
	.string "quand je pars ?\l"
	.string "{PLAYER}{KUN}, aide-moi !$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "OK, compris.\n"
	.string "Je trouverai le temps de dire ça !\p"
	.string "Honnêtement, je suis content\l"
	.string "d'avoir\n"
	.string "un bon mentor comme toi.\p"
	.string "Je vais me débrouiller\l"
	.string "pour avoir du temps\n"
	.string "et faire des combats.\p"
	.string "Merci pour tout,\l"
	.string "{PLAYER}{KUN} !\n"
	.string "On doit se battre un jour, toi et moi !$"
gText_ApprenticePickWinSpeech6::
	.string "J'ai encore eu de la chance !\n"
	.string "{PLAYER} ! Je suis trop content\l"
	.string "de te voir !\l"
	.string "Comme d'habitude, j'ai besoin\l"
	.string "de tes conseils !\p"
	.string "Roulement de tambour !\n"
	.string "Ma dernière question, c'est…\p"
	.string "Si je gagne un combat\l"
	.string "et que je veux le\n"
	.string "finir avec style, qu'est-ce que\l"
	.string "je dois dire ?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Ça… C'est fabuleux !\n"
	.string "C'est digne et stylé ! Je le prends !\p"
	.string "…Dis, tu crois pas que je deviens\n"
	.string "plutôt bon à ça ?\p"
	.string "Alors je pense défier d'autres\n"
	.string "DRESSEURS, désormais.\p"
	.string "{PLAYER}, tes conseils m'ont vraiment aidé.\p"
	.string "Peut-être qu'un jour,\n"
	.string "on se battra !\p"
	.string "Merci pour tout !$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "Je suis si content\l"
	.string "de t'avoir rencontré !\p"
	.string "Je n'ai plus aucun souci\n"
	.string "concernant mes POKéMON.\p"
	.string "C'est moi qui m'inquiète…\p"
	.string "Tu sais comment un DRESSEUR dit\n"
	.string "quelques mots quand il gagne un combat ?\p"
	.string "J'aimerais vraiment faire pareil,\n"
	.string "moi aussi !\p"
	.string "S'il te plaît,\l"
	.string "qu'est-ce que je dois dire\n"
	.string "quand je gagne un combat ?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah ! Cette phrase !\l"
	.string "Elle me rafraîchit\n"
	.string "et me donne l'impression de renaître !\p"
	.string "Je dois l'utiliser tout de suite !\p"
	.string "Et maintenant, je dois prendre congé,\n"
	.string "{PLAYER}…\p"
	.string "Je vais aller défier\l"
	.string "beaucoup d'autres personnes,\n"
	.string "mais je n'oublierai jamais\l"
	.string "tes enseignements.\p"
	.string "Peut-être qu'un jour…\n"
	.string "Adieu !$"

gText_ApprenticePickWinSpeech8::
	.string "Aïe ! J'ai repéré {PLAYER} !\n"
	.string "Je… je suis trop content de te voir !\p"
	.string "Oh-oh-oh ! Y a un truc que je devais\n"
	.string "absolument te demander !\p"
	.string "Il y a pas longtemps, j'ai gagné un combat.\n"
	.string "Ça, c'était grisant !\p"
	.string "Mais j'étais si content que\n"
	.string "j'ai eu la gorge nouée et j'ai rien pu dire !\p"
	.string "Alors maintenant, {PLAYER},\l"
	.string "s'il te plaît,\n"
	.string "trouve-moi une phrase\l"
	.string "de sortie quand je gagne !$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "Je vais dire ça ?!\l"
	.string "Je… je suis fou de joie !\p"
	.string "M-m-merci !\n"
	.string "Je n'ai plus rien à regretter maintenant !\p"
	.string "Je vais partir voyager et combattre\n"
	.string "toutes sortes de gens.\p"
	.string "Je te dois tout, {PLAYER}.\n"
	.string "Vraiment, vraiment, merci !\p"
	.string "Je dois y aller, mais un jour,\n"
	.string "on se battra !$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Tu sais, j'ai envie de partir\n"
	.string "en vadrouille et faire des combats.\p"
	.string "Mais avant ça,\l"
	.string "j'veux encore ton avis,\n"
	.string "s'il te plaît !\p"
	.string "Si je gagne un combat,\l"
	.string "quelle vantardise\n"
	.string "je peux dire à mon adversaire\l"
	.string "DRESSEUR vaincu ?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, c'est parfait !\n"
	.string "Si, bueno!\l"
	.string "J'vais dire ça, genre, bam !\p"
	.string "Et maintenant, c'est l'heure\l"
	.string "de dire au revoir !\n"
	.string "Merci pour tout, vraiment !\p"
	.string "Donne-moi un combat un jour, OK ?\n"
	.string "Adios !$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, gros problème !\p"
	.string "Quand je gagne un combat, je m'en vante\n"
	.string "au moins pendant une heure !\p"
	.string "Bien sûr que je mens !\n"
	.string "Wahahaha !\p"
	.string "Mais ça, c'est vrai.\n"
	.string "Je suis pas très bon pour parler.\p"
	.string "Alors, tu peux décider\l"
	.string "pour moi ce que\n"
	.string "je dois dire après avoir gagné,\l"
	.string "maître ?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "C'est ça que je dois dire, hein ?\n"
	.string "Alors je vais éviter de dire ça !\p"
	.string "Je plaisante !\n"
	.string "Je suivrai ton enseignement, maître !\p"
	.string "Merci pour tout ce\l"
	.string "que tu m'as appris,\n"
	.string "maître !\p"
	.string "Je comprends enfin\l"
	.string "ce que ça veut dire\n"
	.string "d'être un DRESSEUR.\p"
	.string "Je vais sortir et gagner des combats\n"
	.string "contre n'importe quel DRESSEUR.\p"
	.string "Peut-être que ce sera toi, un jour, maître !\p"
	.string "C'est tout !\n"
	.string "Adieu, mon maître !$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "Ça se lit “ahoy” !\p"
	.string "The rappin' SAILOR am I!\n"
	.string "C'est ma dernière question,\l"
	.string "ne pleure pas !\p"
	.string "C'est une question de phrase\n"
	.string "et j'attends ta suggestion !\p"
	.string "Si je gagne un match,\l"
	.string "qu'est-ce que je peux dire\n"
	.string "d'une façon vraiment stylée ?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Parfait ! Je vais dire ça.\n"
	.string "J'ai bien fait de te faire choisir !\p"
	.string "Et maintenant, je crois que le mieux,\n"
	.string "c'est que je prenne mon envol !\p"
	.string "Merci pour tout ce\l"
	.string "que tu m'as appris.\n"
	.string "J'pars enchaîner les combats !\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "Et ça s'écrit bon voyage,\l"
	.string "à toi, mon hommage !$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, yeah, {PLAYER} !\n"
	.string "Je t'ai encore trouvé aujourd'hui !\p"
	.string "Je fais quoi ? Je te redemande ?\n"
	.string "Pourquoi pas ? Je te demande déjà !\p"
	.string "Bref, {PLAYER}…\n"
	.string "Tu me reçois ?\l"
	.string "Tu me reçois !\l"
	.string "J'ai encore besoin de tes conseils !\p"
	.string "C'est pour ce que je dois crier.\n"
	.string "Un truc stylé à hurler quand\l"
	.string "le combat se finit bien.\p"
	.string "Allez, j'veux t'entendre le dire !$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "D'accord, d'accord !\n"
	.string "Je vais dire ça,\l"
	.string "parce que c'est trop stylé !\p"
	.string "Je n'ai plus rien à te demander.\n"
	.string "Il ne me reste qu'à te dire au revoir.\p"
	.string "Mais peut-être qu'un jour on se reverra,\n"
	.string "avec l'un de nous deux qui perdra.\p"
	.string "Mais pour l'instant,\l"
	.string "il est temps de se dire adieu.\p"
	.string "Bon, {PLAYER}, je dois filer,\n"
	.string "mais ne m'oublie pas !\p"
	.string "Prends soin de toi,\l"
	.string "{PLAYER} !\n"
	.string "Je t'adore !$"
gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, je suis fini…\n"
	.string "Mon nez n'arrête pas de couler…\p"
	.string "J'essayais de trouver un truc\n"
	.string "stylé à dire quand je gagne un combat.\p"
	.string "Ça m'a tellement inspiré que j'ai pleuré,\n"
	.string "et maintenant mon nez n'arrête pas de couler…\p"
	.string "Donc, vu la situation,\n"
	.string "j'ai besoin que tu\l"
	.string "décides pour moi,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Quand je gagne un combat,\n"
	.string "qu'est-ce que je dois dire ?$"
gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …C'est bien.\n"
	.string "Non, c'est inspirant !\l"
	.string "Ça me fait monter de nouvelles larmes !\p"
	.string "Mais malgré mes larmes\l"
	.string "et mon nez qui coule,\n"
	.string "je vais utiliser cette phrase !\p"
	.string "J'ai plus rien à te demander,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Désormais, on est rivaux !\n"
	.string "Merci pour tout !$"

gText_ApprenticePickWinSpeech14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "S'il te plaît, ne me\l"
	.string "regarde pas comme ça.\n"
	.string "Ça me rend trop nerveux.\p"
	.string "Je… j'ai encore besoin de tes conseils.\n"
	.string "Mais ce sera la dernière fois…\p"
	.string "C'est vraiment gênant à demander,\n"
	.string "mais si je gagne un combat ?\l"
	.string "Qu'est-ce que je dois dire ?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… D'accord !\n"
	.string "Je vais essayer de dire ça !\l"
	.string "Je serai peut-être\l"
	.string "trop nerveux pour le dire…\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Je dois te dire au revoir maintenant.\p"
	.string "Je suivrai tout ce\l"
	.string "que tu m'as appris,\l"
	.string "{PLAYER}{KUN}, et je ferai\l"
	.string "de mon mieux.$"

gText_ApprenticePickWinSpeech15::
	.string "Hmm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais est-ce bien toi ?\l"
	.string "Peut-être une POUPÉE\l"
	.string "{PLAYER} rusée ?\p"
	.string "Oh, non, non, non,\l"
	.string "ne t'inquiète pas !\n"
	.string "Si tu es vraiment réel,\l"
	.string "oublie mon impolitesse.\p"
	.string "Pas besoin de te fâcher.\l"
	.string "Ce que je veux,\n"
	.string "c'est encore ton précieux avis.\p"
	.string "Cela concerne une phrase.\p"
	.string "Plus précisément,\l"
	.string "qu'est-ce que je dois dire\n"
	.string "si je gagne un combat ?$"
gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Quand je gagne un match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Tu es sérieux ?\p"
	.string "Je vois. Si tu es sérieux, ça me va.\n"
	.string "Merci pour ton temps.\p"
	.string "J'espère que même moi, je pourrai\n"
	.string "faire bon usage de cette phrase.\p"
	.string "Il semble que je n'aie plus besoin\n"
	.string "de conseils.\p"
	.string "Je crois qu'il est grand\l"
	.string "temps de te\n"
	.string "dire adieu et partir de mon côté.\p"
	.string "Merci, mon mentor !\n"
	.string "Pardonne mon scepticisme !$"
