gText_Birch_Welcome::
	.string "Bonjour! Désolé pour l'attente!\p"
	.string "Bienvenue dans le monde\n"
	.string "des POKéMON!\p"
	.string "Je m'appelle CHEN.\p"
	.string "Mais tout le monde ici m'appelle\n"
	.string "le PROFESSEUR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Voici ce qu'on appelle un “POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "appelées POKéMON.\p"
	.string "Nous, les humains, vivons avec les\n"
	.string "POKéMON. Il nous arrive de jouer\l"
	.string "ou de travailler ensemble.\p"
	.string "Et parfois, nous nous réunissons\n"
	.string "pour nous affronter au cours de\l"
	.string "formidables combats de POKéMON.\p"
	.string "Mais malgré nos liens, nous ne\n"
	.string "savons pas tout sur les POKéMON.\p"
	.string "En réalité, il existe d'innombrables\n"
	.string "secrets concernant les POKéMON.\p"
	.string "Pour percer les mystères des\n"
	.string "POKéMON, je les étudie. C'est\l"
	.string "mon métier, je suis chercheur.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Et toi, qui es-tu?$"

gText_Birch_BoyOrGirl::
	.string "Es-tu un garçon?\n"
	.string "Ou es-tu une fille?$"

gText_Birch_Difficulty::
	.string "Ah oui…\p"
	.string "Et… Comment penses-tu que cette\n"
	.string "aventure va se dérouler?$"

gText_Birch_LockDifficulty::
	.string "Si tu dois changer la DIFFICULTÉ\n"
	.string "tu peux ouvrir le MENU OPTIONS\l"
	.string "et la modifier.\p"
	.string "Tu peux aussi la verrouiller,\n"
	.string "si tu le souhaites.\l"
	.string "Veux-tu verrouiller la\l"
	.string "DIFFICULTÉ choisie ?\p"
	.string "Ce choix sera définitif.$"

gText_Birch_Challenge::
	.string "Oh, vraiment ?\p"
	.string "Très bien, maintenant que c'est\n"
	.string "réglé… T'attends-tu à relever\l"
	.string "des DÉFIS au cours de ton\l"
	.string "voyage ?\p"
	.string "Et comment t'appelles-tu ?$"

gText_Birch_WhatsYourName::
	.string "Très bien.\n"
	.string "Comment t'appelles-tu?$"

gText_Birch_SoItsPlayer::
	.string "Tu t'appelles {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, mais c'est vrai!\p"
	.string "Tu es {PLAYER}{KUN}! Tu viens d'arriver\n"
	.string "à BOURG GEON.\p"
	.string "Je m'en souviens, maintenant!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bon, comment te sens-tu?\p"
	.string "Tu es sur le point de commencer\n"
	.string "une aventure unique.\p"
	.string "Fais preuve de courage et plonge\n"
	.string "dans le monde des POKéMON où\l"
	.string "tu vivras de belles aventures,\l"
	.string "remplies de rêves et d'amitiés!\p"
	.string "On se revoit plus tard !\p"
	.string "$"
