BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MAÎTRE MIXEUR : En effet !\n"
	.string "Je suis le MAÎTRE MIXEUR !\p"
	.string "Mélange avec moi et tu verras\n"
	.string "la maîtrise que j'apporte au mixage !$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MAÎTRE MIXEUR : Hmmm ! Tu veux\n"
	.string "voir ma maîtrise en action ?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm !\p"
	.string "Tu es trop occupé, je vois !\p"
	.string "Mais ne crains rien !\n"
	.string "Je serai là toute la journée !\l"
	.string "Reviens quand tu auras le temps !$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm !\p"
	.string "Tu n'as pas une seule BAIE !\p"
	.string "Je serai là toute la journée !\n"
	.string "Reviens vite avec des BAIES !$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Bien sûr !\n"
	.string "Bien sûr !\p"
	.string "Au fait…\n"
	.string "Tu sais mélanger des {POKEBLOCK}S\l"
	.string "à partir des BAIES ?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm !\p"
	.string "C'est un processus simple !\p"
	.string "Quand la flèche du MIXEUR arrive\n"
	.string "sur ton marqueur, appuie sur A.\p"
	.string "C'est tout ce que tu as à faire.\p"
	.string "Quand tu verras avec quelle précision\n"
	.string "j'appuie sur A, tu comprendras.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Parfait !\p"
	.string "Commençons alors !\p"
	.string "Tous ensemble avec le MAÎTRE MIXEUR,\n"
	.string "en avant pour le MIXEUR À BAIES !$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm !\p"
	.string "Tu n'as pas l'air d'avoir\n"
	.string "la BOÎTE À {POKEBLOCK}S !\p"
	.string "Je serai là toute la journée !\n"
	.string "Obtiens la BOÎTE À {POKEBLOCK}S et reviens !$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm !\p"
	.string "Ta BOÎTE À {POKEBLOCK}S est pleine !\p"
	.string "Je serai là toute la journée !\n"
	.string "Utilise des {POKEBLOCK}S et reviens !$"

BerryBlender_Text_WhoaAwesome:
	.string "Waouh !\n"
	.string "Impressionnant !$"

BerryBlender_Text_WickedlyFast:
	.string "D'une rapidité fulgurante !$"

BerryBlender_Text_WhatAnExpert:
	.string "Quel expert !$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Avec le MAÎTRE, nous avons fait\n"
	.string "d'incroyables {POKEBLOCK}S !$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Un regard qui suit la flèche avec\n"
	.string "une intensité mécanique…\p"
	.string "Une main qui appuie sur A avec\n"
	.string "une précision d'horloger…\p"
	.string "Ces qualités font du MAÎTRE MIXEUR\n"
	.string "un véritable maître.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Le MAÎTRE MIXEUR s'entraînerait\n"
	.string "au fond des montagnes.\p"
	.string "Il vient parfois à JADIELLE pour\n"
	.string "mélanger des BAIES toute la journée.$"
