@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Une capacité très séduisante.$"

gText_UserMoreEasilyStartled::
	.string "Après cette capacité, le lanceur\n"
	.string "est plus facilement déstabilisé.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Fait une super prestation, mais\n"
	.string "ne peut plus jouer ensuite.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Peut être utilisée souvent\n"
	.string "sans lasser le JUGE.$"

gText_AvoidStartledByOthersOnce::
	.string "Évite d'être déstabilisé\n"
	.string "par les autres une fois.$"

gText_AvoidStartledByOthers::
	.string "Évite d'être déstabilisé\n"
	.string "par les autres.$"

gText_AvoidStartledByOthersLittle::
	.string "Évite un peu d'être déstabilisé\n"
	.string "par les autres.$"

gText_UserLessLikelyStartled::
	.string "Après cette capacité, le lanceur\n"
	.string "est moins facilement déstabilisé.$"

gText_SlightlyStartleFrontMon::
	.string "Déstabilise un peu le\n"
	.string "POKéMON devant.$"

gText_SlightlyStartleAppealed::
	.string "Déstabilise un peu ceux\n"
	.string "qui ont fait une prestation.$"

gText_StartleAppealedBeforeUser::
	.string "Déstabilise le POKéMON qui\n"
	.string "est passé avant le lanceur.$"

gText_StartleAllAppealed::
	.string "Déstabilise tous les POKéMON qui\n"
	.string "ont déjà fait leur prestation.$"

gText_BadlyStartleFrontMon::
	.string "Déstabilise beaucoup le\n"
	.string "POKéMON devant.$"

gText_BadlyStartleAppealed::
	.string "Déstabilise beaucoup ceux\n"
	.string "qui ont fait une prestation.$"

gText_StartleAppealedBeforeUser2::
	.string "Déstabilise le POKéMON qui\n"
	.string "est passé avant le lanceur.$"

gText_StartleAllAppealed2::
	.string "Déstabilise tous les POKéMON qui\n"
	.string "ont déjà fait leur prestation.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Détourne l'attention du JUGE\n"
	.string "des autres.$"

gText_StartleMonHasJudgesAttention::
	.string "Déstabilise le POKéMON qui\n"
	.string "attire l'attention du JUGE.$"

gText_JamOthersMissesTurn::
	.string "Gêne les autres, puis rate\n"
	.string "un tour de prestation.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Déstabilise les POKéMON ayant\n"
	.string "fait une prestation du même type.$"

gText_BadlyStartleCoolAppeals::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "ayant fait du SANG-FROID.$"

gText_BadlyStartleBeautyAppeals::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "ayant fait de la BEAUTE.$"

gText_BadlyStartleCuteAppeals::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "ayant fait de la GRACE.$"

gText_BadlyStartleSmartAppeals::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "ayant fait de l'INTELLIGENCE.$"

gText_BadlyStartleToughAppeals::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "ayant fait de la ROBUSTESSE.$"

gText_MakeMonAfterUserNervous::
	.string "Rend nerveux un POKéMON\n"
	.string "après le lanceur.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Rend nerveux tous les POKéMON\n"
	.string "après le lanceur.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Dégrade la condition de ceux\n"
	.string "qui ont fait une prestation.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "en bonne condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "La prestation est géniale si\n"
	.string "elle est faite en premier.$"

gText_AppealGreatIfPerformedLast::
	.string "La prestation est géniale si\n"
	.string "elle est faite en dernier.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Rend la prestation aussi bonne\n"
	.string "que celles d'avant.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Rend la prestation aussi bonne\n"
	.string "que la précédente.$"

gText_AppealBetterLaterItsPerformed::
	.string "La prestation est meilleure\n"
	.string "plus elle est faite tard.$"

gText_AppealVariesDependingOnTiming::
	.string "La qualité varie selon\n"
	.string "le moment où elle est faite.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Marche bien si c'est le même\n"
	.string "type que la précédente.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Marche bien si c'est d'un\n"
	.string "type différent de la précédente.$"

gText_AffectedByAppealInFront::
	.string "Dépend de la qualité de la\n"
	.string "prestation juste avant.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Améliore la condition du lanceur.\n"
	.string "Aide à éviter la nervosité.$"

gText_AppealWorksWellIfConditionGood::
	.string "La prestation marche bien si la\n"
	.string "condition du lanceur est bonne.$"

gText_NextAppealMadeEarlier::
	.string "La prochaine prestation peut être\n"
	.string "faite plus tôt au prochain tour.$"

gText_NextAppealMadeLater::
	.string "La prochaine prestation peut être\n"
	.string "faite plus tard au prochain tour.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Rend l'ordre du prochain tour\n"
	.string "plus facile à mélanger.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Mélange l'ordre des\n"
	.string "prestations au prochain tour.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Une prestation qui excite le\n"
	.string "public dans tout CONCOURS.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Déstabilise beaucoup les POKéMON\n"
	.string "ayant fait de bonnes prestations.$"

gText_AppealBestMoreCrowdExcited::
	.string "La prestation est meilleure quand\n"
	.string "le public est plus excité.$"

gText_TemporarilyStopCrowdExcited::
	.string "Stoppe temporairement\n"
	.string "l'excitation du public.$"

@ Unused move names

gText_RainDance::
	.string "DANSE PLUIE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "PUISSANCE$"

gText_Hypnosis::
	.string "HYPNOSE$"

gText_Softboiled::
	.string "E-COQUE$"

gText_HornAttack::
	.string "KOUD'KORNE$"

gText_SwordsDance::
	.string "DANSE-LAMES$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "ZENITH$"

gText_Rest2::
	.string "REPOS$"

gText_Vicegrip::
	.string "ETREINTE$"

gText_DefenseCurl::
	.string "BOUL'ARMURE$"

gText_LockOn::
	.string "VERROUILLAGE$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "SANG-FROID$"

gContestMoveTypeBeautyText::
	.string "BEAUTE$"

gContestMoveTypeCuteText::
	.string "GRACE$"

gContestMoveTypeSmartText::
	.string "INTELLIGENCE$"

gContestMoveTypeToughText::
	.string "ROBUSTESSE$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Prestation No {STR_VAR_1}!\n"
	.string "Quelle capacité utiliser?$"

gText_AppealNumButItCantParticipate::
	.string "Prestation No {STR_VAR_1}!\n"
	.string "Mais il ne peut pas participer!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} a fait sa prestation\n"
	.string "avec {STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} observait\n"
	.string "les autres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Fin du Temps de\n"
	.string "prestation!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Mais la prestation a été\n"
	.string "gênée.$"

gText_FollowedAnotherMonsLead::
	.string "Il a suivi l'exemple\n"
	.string "d'un autre POKéMON.$"

gText_ButItMessedUp::
	.string "Mais il s'est loupé.$"

gText_WentBetterThanUsual::
	.string "Ça s'est mieux passé\n"
	.string "que d'habitude.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Le JUGE a détourné les yeux\n"
	.string "sans raison apparente.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Il a tout donné pour\n"
	.string "rattraper ses erreurs.$"

gText_CantMakeAnyMoreMoves::
	.string "Il ne peut plus faire\n"
	.string "de prestations.$"

gText_WorkedFrighteninglyWell::
	.string "Ça a marché terriblement\n"
	.string "bien.$"

gText_WorkedHardAsStandoutMon::
	.string "Il a autant assuré que le\n"
	.string "POKéMON vedette.$"

gText_JudgedLookedOnExpectantly::
	.string "Le JUGE regardait avec\n"
	.string "impatience.$"

gText_WorkedRatherWell::
	.string "Ça a plutôt bien marché.$"

gText_WorkedLittleBetterThanUsual::
	.string "Ça a un peu mieux marché\n"
	.string "que d'habitude.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} n'a pas du tout\n"
	.string "fait sensation…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} n'a pas beaucoup\n"
	.string "fait sensation…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} a attiré un\n"
	.string "peu l'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} a beaucoup attiré\n"
	.string "l'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} a capté\n"
	.string "l'attention totale.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} n'a pas encore\n"
	.string "fait sa prestation.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "L'attente grandit pour la\n"
	.string "prochaine prestation de {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "Le JUGE garde son avis\n"
	.string "sur {STR_VAR_1}.$"

gText_MonsXChangedPerceptions::
	.string "Le {STR_VAR_3} de {STR_VAR_1}\n"
	.string "a changé les esprits.$"

gText_MonsAppealEffectWoreOff::
	.string "L'effet de la prestation\n"
	.string "de {STR_VAR_1} s'est dissipé.$"

gText_SpecialAppealsEffectWoreOff::
	.string "L'effet de la prestation\n"
	.string "spéciale s'est dissipé.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Toutes les prestations\n"
	.string "se ressemblent désormais.$"

gText_CheapenedMonsAppeal::
	.string "Ça a diminué la prestation\n"
	.string "de {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Ça a diminué la prestation\n"
	.string "de ceux devant.$"

gText_StoleAttentionAwayFromMon::
	.string "Ça a volé l'attention\n"
	.string "à {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Ça a diminué la prestation\n"
	.string "de {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Ça a fortement diminué\n"
	.string "les autres prestations.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "L'attente grandit pour la\n"
	.string "prochaine prestation de {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Ça a diminué la prestation\n"
	.string "de ceux devant.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Ça a diminué la prestation\n"
	.string "préférée du JUGE.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Les prestations des autres\n"
	.string "ont été réduites de moitié.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Il s'est démarqué pour\n"
	.string "compenser la gêne.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Il ne peut plus participer\n"
	.string "aux prestations.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Le JUGE a été ému par\n"
	.string "une superbe prestation.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "L'attente monte pour les\n"
	.string "prestations à venir.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Il s'est autant démarqué que\n"
	.string "les prestations spéciales.$"

gText_StoodOutAsMuchAsMon::
	.string "Il s'est autant démarqué que\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Les prestations gênées sont\n"
	.string "encore moins remarquées.$"

gText_EveryonesAppealsMadeSame::
	.string "Toutes les prestations ont\n"
	.string "été rendues identiques.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Il a fait plus attention\n"
	.string "aux autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} ne peut plus\n"
	.string "faire de prestation ensuite.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Il s'est calmé\n"
	.string "un tout petit peu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Il a ignoré\n"
	.string "les autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Il a fait moins attention\n"
	.string "aux autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Il ne se soucie presque plus\n"
	.string "des autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Il a tenté de déstabiliser\n"
	.string "les autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Il a tenté d'éblouir\n"
	.string "les autres.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Le JUGE a détourné les yeux\n"
	.string "de {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Il a tenté de rendre nerveux\n"
	.string "le prochain POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} est devenu\n"
	.string "nerveux.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "La prestation a tenté de rendre\n"
	.string "nerveux les POKéMON en attente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Il a provoqué les POKéMON\n"
	.string "qui s'en sortent bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} a repris\n"
	.string "ses esprits.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Il a tenté de gêner les POKéMON\n"
	.string "qui s'en sortent bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "La vedette {STR_VAR_1}\n"
	.string "a redoublé d'efforts.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Le discret\n"
	.string "{STR_VAR_1} a fait de son mieux.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Il a assuré autant que le\n"
	.string "POKéMON juste avant.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "La prestation de {STR_VAR_1}\n"
	.string "ne s'est pas bien passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Il a assuré autant que le\n"
	.string "POKéMON précédent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "La prestation de {STR_VAR_1}\n"
	.string "ne s'est pas bien passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "La prestation de {STR_VAR_1}\n"
	.string "ne s'est pas bien passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "La prestation de {STR_VAR_1}\n"
	.string "ne s'est pas trop mal passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "La prestation de {STR_VAR_1}\n"
	.string "s'est assez bien passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "La prestation de {STR_VAR_1}\n"
	.string "s'est passée à merveille.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "La prestation de {STR_VAR_1}\n"
	.string "a fait un flop.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "La prestation de {STR_VAR_1}\n"
	.string "n'a pas très bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "La prestation de {STR_VAR_1}\n"
	.string "ne s'est pas trop mal passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "La prestation de {STR_VAR_1}\n"
	.string "s'est assez bien passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "La prestation de {STR_VAR_1}\n"
	.string "s'est très bien passée.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "La prestation de {STR_VAR_1}\n"
	.string "s'est passée à merveille.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "C'est le même type que le\n"
	.string "POKéMON d'avant--bien!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Ce n'est pas le même type que\n"
	.string "le précédent--bien!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Il s'est bien plus démarqué\n"
	.string "que le POKéMON d'avant.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Il n'a pas fait aussi bien que\n"
	.string "le POKéMON d'avant.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "La condition de {STR_VAR_1}\n"
	.string "a dépassé la normale.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "L'état chaud de {STR_VAR_1}\n"
	.string "a rendu sa prestation super!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Il avance dans la file pour\n"
	.string "la prochaine prestation.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Il recule d'une place pour\n"
	.string "la prochaine prestation.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Il a mélangé l'ordre\n"
	.string "au prochain tour.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Le JUGE regarde\n"
	.string "{STR_VAR_1} avec impatience.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Le combo de prestations a\n"
	.string "bien plu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Le combo de prestations a\n"
	.string "beaucoup plu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Le combo de prestations\n"
	.string "a fait sensation.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} a réussi\n"
	.string "à détourner le regard.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} a réussi\n"
	.string "à ne pas le voir.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} n'est pas troublé\n"
	.string "par ce genre de chose.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} est devenu\n"
	.string "un peu distrait.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Il a tenté de déstabiliser\n"
	.string "les autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} a baissé les yeux,\n"
	.string "distrait.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} s'est retourné,\n"
	.string "distrait.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} n'a pu s'empêcher\n"
	.string "de pousser un cri.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} n'a pu s'empêcher\n"
	.string "de bondir.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} a trébuché,\n"
	.string "distrait.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} est trop\n"
	.string "nerveux pour bouger.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Mais il s'est loupé.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Mais il n'a pas réussi à rendre\n"
	.string "la cible nerveuse.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Mais il n'a rendu\n"
	.string "personne nerveux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Mais il a été ignoré…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Mais il n'a pas pu améliorer\n"
	.string "sa condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Sa mauvaise condition\n"
	.string "lui donne une prestation faible.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} n'est pas\n"
	.string "affecté.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} est déçu\n"
	.string "d'avoir répété.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "Le {STR_VAR_3} de {STR_VAR_1}\n"
	.string "a fait sensation.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "Le {STR_VAR_3} de {STR_VAR_1}\n"
	.string "n'a pas plu ici…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "Le {STR_VAR_3} de {STR_VAR_1}\n"
	.string "a chauffé le public.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} ne peut pas jouer\n"
	.string "au prochain tour…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Il a attiré l'attention\n"
	.string "du public.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Le public continue de\n"
	.string "regarder {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "Le {STR_VAR_2} de\n"
	.string "{STR_VAR_1} est ignoré.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "timidité$"

gText_Contest_Anxiety::
	.string "anxiété$"

gText_Contest_Laziness::
	.string "paresse$"

gText_Contest_Hesitancy::
	.string "hésitation$"

gText_Contest_Fear::
	.string "peur$"

gText_Contest_Coolness::
	.string "sang-froid$"

gText_Contest_Beauty::
	.string "beauté$"

gText_Contest_Cuteness::
	.string "grâce$"

gText_Contest_Smartness::
	.string "intelligence$"

gText_Contest_Toughness::
	.string "robustesse$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "Capacité SANG-FROID$"

gText_BeautyMove::
	.string "Capacité BEAUTE$"

gText_CuteMove::
	.string "Capacité GRACE$"

gText_SmartMove::
	.string "Capacité INTELLIGENCE$"

gText_ToughMove::
	.string "Capacité ROBUSTESSE$"

gText_3QuestionMarks::
	.string "???$"
