@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Tour manqué$"

gText_LinkStandby4::
	.string "Connexion en attente !$"

gText_WinnerIsPlayersMonCongrats::
	.string "Le gagnant est {STR_VAR_2} de {STR_VAR_1} !\n"
	.string "Félicitations !$"

gText_WinnerIsPlayersMon::
	.string "Le gagnant est {STR_VAR_2} de {STR_VAR_1} !{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Jugement principal : No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Jugement secondaire : No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Épreuve imposée : No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Attaque la plus utilisée :\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "POKéMON le plus impressionnant :\n"
	.string "{STR_VAR_2} de {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Épreuve imposée : No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Aucune émission TV link ne sera\n"
	.string "réalisée : le DRESSEUR a perdu.{PAUSE_UNTIL_PRESS}$"
