	.align 2
gText_ConfirmSave::
	.string "Voulez-vous sauvegarder la partie?$"

gText_AlreadySavedFile::
	.string "Il y a déjà une partie sauvegardée.\nVoulez-vous la remplacer?$"

gText_SavingDontTurnOff::
	.string "SAUVEGARDE EN COURS…\nN'ETEIGNEZ PAS LA CONSOLE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "ATTENTION !\p"
	.string "Il y a déjà un fichier de\n"
	.string "sauvegarde différent.\p"
	.string "Si vous sauvegardez maintenant,\n"
	.string "l'aventure de l'autre fichier,\l"
	.string "y compris les objets et les\l"
	.string "POKéMON, sera totalement perdue.\p"
	.string "Voulez-vous vraiment sauvegarder\n"
	.string "et écraser l'autre fichier ?$"

gText_SaveError::
	.string "Erreur de sauvegarde.\p"
	.string "Veuillez changer la\n"
	.string "mémoire de secours.$"

gText_SavingDontTurnOffPower::
	.string "SAUVEGARDE…\n"
	.string "N'ÉTEIGNEZ PAS LA CONSOLE.$"
